import { explorations } from './explorations.mjs';
export const catalog = [
  { title: 'Punnett square calculator', description: 'Cross two parents for one trait, two traits, or ABO blood type and see genotype and phenotype ratios with steps.', href: '/punnett-square-calculator/', category: 'Genetics', icon: '⊞', meta: 'Monohybrid · dihybrid · blood type', keywords: 'heredity dominant recessive genotype phenotype cross' },
  { title: 'DNA transcription & translation', description: 'Turn a DNA sequence into mRNA codons and an amino-acid chain, with the genetic code table and reverse complement.', href: '/dna-transcription-translation/', category: 'Molecular', icon: '⌇', meta: 'Codon-by-codon output', keywords: 'mrna protein codon amino acid gene sequence' },
  { title: 'Population growth calculator', description: 'Compare exponential and logistic growth, find doubling time, and read the growth curve.', href: '/population-growth-calculator/', category: 'Ecology', icon: '↗', meta: 'Exponential + logistic', keywords: 'carrying capacity rate curve' },
  { title: 'Hardy-Weinberg calculator', description: 'Find allele and genotype frequencies from p, q, or observed counts, then test a population for equilibrium.', href: '/hardy-weinberg-calculator/', category: 'Genetics', icon: 'p²', meta: 'p² + 2pq + q² = 1', keywords: 'allele frequency equilibrium evolution' },
  ...explorations.map(t => ({ title: t.title, description: t.description, href: '/tools/' + t.slug + '/', category: t.category, icon: t.icon, meta: t.meta || 'Visual explanation + steps', keywords: t.keywords || '' })),
  { title: 'Cell atlas', description: 'Compare organelles: where each is found, what it does, and how the parts of a cell work together.', href: '/cells/', category: 'Cells', icon: '◉', meta: 'Eight organelle guides', keywords: 'organelle nucleus mitochondria chloroplast diagram' },
  { title: 'Printable diagrams', description: 'Download or print cell diagrams to label and blank Punnett square grids, with optional answer keys.', href: '/printable-diagrams/', category: 'Reference', icon: '▤', meta: 'SVG + print to PDF', keywords: 'worksheet label animal plant cell' },
  { title: 'Worksheet builder', description: 'Create a printable biology practice sheet with an optional answer key.', href: '/worksheets/', category: 'Practice', icon: '▤', meta: '8, 12, or 20 questions', keywords: 'quiz printable' },
  { title: 'Practice studio', description: 'Take a short quiz, read explanations, and review your mistakes.', href: '/practice/', category: 'Practice', icon: '✓', meta: 'Five topics + mixed practice', keywords: 'quiz questions test' },
  { title: 'Concept notes', description: 'Learn the idea, work through an example, and avoid common mistakes.', href: '/learn/', category: 'Reference', icon: 'ƒ', meta: 'Sixteen concept guides', keywords: 'lessons explained revision' },
];
