// Editorial questions are rendered into the page HTML (and FAQPage JSON-LD), including collapsed answers.
// Every href is an internal route; every number matches what the corresponding tool actually computes.
const q = (question, answer, href, label) => ({ question, answer, href, label });
export const faqs = {
  home: [
    q('What can I do with Biology Lab?', 'Cross two parents in a Punnett square, translate a DNA sequence into protein, model exponential and logistic population growth, test a population for Hardy-Weinberg equilibrium, and explore nine more calculators from enzyme kinetics to energy pyramids. Each tool pairs the result with a live diagram and worked steps that update as you change the inputs.', '/tools/', 'Explore all tools'),
    q('Is Biology Lab free to use?', 'Yes. The calculators, the cell atlas, the concept lessons, practice rounds, worksheets, and printable diagrams are all free, with no account and no sign-up. Every calculation runs in your browser, so nothing you type is sent to a server.', '/about/', 'About the lab'),
    q('Which tool should I use for a genetics cross?', 'Start with the Punnett square calculator. It handles monohybrid crosses such as Aa × Aa (3 : 1), dihybrid crosses such as AaBb × AaBb (9 : 3 : 3 : 1), up to three genes, and ABO blood types with an optional Rh factor. To check whether real offspring counts fit the predicted ratio, follow up with the chi-square test.', '/punnett-square-calculator/', 'Open the Punnett square calculator'),
    q('Can I see how an answer is calculated?', 'Yes. Every calculator shows the formula with your numbers substituted and two to four worked steps, and the sixteen concept lessons explain the idea behind each tool with a numeric example and a common misconception. Change an input and watch the steps and the diagram change with it.', '/learn/', 'Read the concept lessons'),
    q('Can I use these resources for teaching or practice?', 'Yes. Try an eight-question practice round with instant explanations across cells, genetics, molecular biology, ecology, and physiology, build a worksheet of 8, 12, or 20 questions with an optional answer key, or print a cell diagram to label and a blank Punnett grid to fill in.', '/worksheets/', 'Create a worksheet'),
  ],
  'punnett-square-calculator': [
    q('How do you fill in a Punnett square?', 'Write one parent’s possible gametes across the top and the other parent’s down the side, then fill each box with one allele from its column and one from its row. For Aa × Aa the four boxes read AA, Aa, Aa, and aa, a 1 : 2 : 1 genotype ratio and, with complete dominance, a 3 : 1 phenotype ratio. The calculator draws the grid exactly this way and counts the boxes for you.', '/learn/mendelian-inheritance/', 'Read: Mendelian inheritance'),
    q('What does a 9:3:3:1 ratio mean?', 'It is the phenotype ratio of a dihybrid cross between two double heterozygotes, AaBb × AaBb. Each parent makes four kinds of gamete (AB, Ab, aB, ab), so the square has 16 boxes: 9 show both dominant traits, 3 show dominant A with recessive b, 3 show recessive a with dominant B, and 1 shows both recessive traits. The ratio only appears when the two genes assort independently and both show complete dominance.', '/tools/chi-square-test/', 'Test real counts against 9 : 3 : 3 : 1'),
    q('How does a blood type Punnett square work?', 'ABO blood type is one gene with three alleles: A and B are codominant and O is recessive to both, so AA and AO are type A, BB and BO are type B, AB is type AB, and OO is type O. A type A parent (AO) and a type B parent (BO) can have children of all four blood types: AB, A (AO), B (BO), and O (OO), each with a 1 in 4 chance. Switch on the Rh factor to add a second gene (D dominant, d recessive) and the grid grows to 16 boxes with + and − signs.', '/practice/', 'Practice genetics questions'),
  ],
  'hardy-weinberg-calculator': [
    q('What is the Hardy-Weinberg equation?', 'For a gene with two alleles, p + q = 1 describes allele frequencies and p² + 2pq + q² = 1 describes genotype frequencies: p² homozygous dominant, 2pq heterozygous, q² homozygous recessive. If p = 0.7, then q = 0.3, and the population is expected to be 49% AA, 42% Aa, and 9% aa. The calculator expands the equation with your numbers and checks that the three terms add to 1.', '/learn/hardy-weinberg-principle/', 'Read: the Hardy-Weinberg principle'),
    q('How do you find allele frequency from the recessive phenotype?', 'Only aa individuals show a recessive trait, so the frequency of the phenotype equals q². Take the square root to get q, then p = 1 − q. Cystic fibrosis affects about 1 in 2,500 newborns, so q² = 0.0004, q = 0.02, p = 0.98, and the carrier frequency 2pq = 0.0392, about 1 person in 26. Choose the q² tab and enter the phenotype frequency as a fraction.', '/practice/', 'Try a Hardy-Weinberg practice round'),
    q('How do you know if a population is in Hardy-Weinberg equilibrium?', 'Count the genotypes, estimate p from the alleles (p = (2AA + Aa) / 2n), and compare the observed counts with the counts p²n, 2pqn, and q²n predicted by the equation using a chi-square test with 1 degree of freedom. If χ² is 3.841 or less at α = 0.05, the population is consistent with equilibrium; if it is larger, something is acting on the gene: selection, non-random mating, migration, mutation, or drift in a small population. Real populations rarely meet all five conditions exactly, which is why the test is useful.', '/learn/natural-selection/', 'See what breaks the equilibrium'),
  ],
  'dna-transcription-translation': [
    q('What is the difference between mRNA and DNA?', 'DNA is a double-stranded helix built on deoxyribose that stores genes and stays in the nucleus, and it uses the bases A, T, G, and C. Messenger RNA is a single strand built on ribose with uracil (U) in place of thymine, copied from one gene and carried to a ribosome. The mRNA has the same sequence as the DNA coding strand with every T replaced by U, which is exactly what the translator shows when you type a coding strand.', '/learn/dna-structure/', 'Read: DNA structure'),
    q('How do you translate a DNA sequence into a protein?', 'Transcribe the coding strand into mRNA by swapping T for U, split the mRNA into three-base codons from the start of the reading frame, and look each codon up in the genetic code: AUG codes for methionine and marks the start, and UAA, UAG, and UGA are stop signals. The demo strand ATGGCCATTGTAATGGGCCGCTGA… gives Met-Ala-Ile-Val-Met-Gly-Arg, seven amino acids, before the UGA at codon 8 ends the chain. Tick “Begin at first AUG” to translate the way a ribosome scans.', '/learn/transcription-and-translation/', 'Read: transcription and translation'),
    q('What is a reading frame and why does it matter?', 'A reading frame is where you start counting codons: beginning at base 1, 2, or 3 splits the same mRNA into three completely different sets of triplets. Inserting or deleting a number of bases that is not a multiple of 3 shifts the frame, so every codon after the change is misread, usually producing a garbled protein and an early stop. Pick frame 1, 2, or 3 in the translator, or edit the sequence to see whether a mutation is silent, missense, nonsense, or a frameshift.', '/cells/ribosome/', 'Meet the ribosome'),
  ],
  'population-growth-calculator': [
    q('What is the difference between exponential and logistic growth?', 'Exponential growth, N(t) = N₀·e^(rt), assumes unlimited resources and gives a J-shaped curve that multiplies by the same factor every time unit. Logistic growth adds a carrying capacity K, dN/dt = rN(1 − N/K), so the curve is S-shaped and levels off as N approaches K. With N₀ = 100, r = 0.1 per hour and t = 10 hours, the exponential model gives about 272 individuals while the logistic model with K = 1,000 gives about 232.', '/learn/population-growth/', 'Read: population growth models'),
    q('How do you calculate doubling time?', 'For exponential growth the doubling time is T₂ = ln 2 / r ≈ 0.693 / r, where r is the per-capita growth rate as a decimal. A rate of 0.1 per hour doubles the population every 6.93 hours; the human population growing at 1.1% per year (r = 0.011) doubles in about 63 years. In the logistic model the same formula only applies while N is far below K.', '/tools/bacterial-growth/', 'Count bacterial doublings'),
    q('What is carrying capacity?', 'Carrying capacity, K, is the largest population an environment can sustain over time given its food, space, and other limits. In the logistic model growth is fastest at exactly N = K/2 and slows to zero as N reaches K; a population that starts above K shrinks back toward it. The calculator reports how long it takes to reach K/2 and marks K on the graph as a dashed line.', '/tools/predator-prey/', 'See populations that cycle instead'),
  ],
  'cell-size': [
    q('Why are cells so small?', 'Everything a cell needs enters through its surface, but everything it has to feed grows with its volume. A cube-shaped cell 10 µm across has a surface area of 600 µm² and a volume of 1,000 µm³, a ratio of 0.6 per µm; doubling the side to 20 µm halves the ratio to 0.3 per µm. Past a certain size, diffusion can no longer deliver oxygen and remove waste fast enough, so cells divide instead of growing further.', '/learn/surface-area-to-volume/', 'Read: surface area to volume ratio'),
    q('How do you calculate the surface area to volume ratio?', 'Divide the surface area by the volume. For a cube of side s, SA : V = 6s² / s³ = 6 / s; for a sphere of radius r, SA : V = 4πr² / (4⁄3 πr³) = 3 / r. A spherical bacterium 1 µm across (r = 0.5 µm) has a ratio of 6 per µm, ten times that of the 10 µm cube, which is one reason bacteria can grow and divide so fast.', '/practice/', 'Practice with cell questions'),
    q('How do large cells get around the SA:V problem?', 'They change shape or stay quiet. Intestinal cells fold their surface into microvilli, mitochondria fold their inner membrane into cristae, neurons stretch into long thin fibers, and a plant cell’s central vacuole pushes its cytoplasm into a thin layer just inside the wall. A frog egg 1,000 µm across can be huge because it stores yolk and has a very low metabolic rate until it starts dividing.', '/cells/mitochondrion/', 'See folding at work in a mitochondrion'),
  ],
  'enzyme-kinetics': [
    q('What does Km mean?', 'The Michaelis constant Km is the substrate concentration at which the reaction runs at exactly half of Vmax. It is a rough measure of affinity: a low Km means the enzyme reaches half speed with very little substrate. Hexokinase has a Km of about 0.05 mM for glucose, so at the 5 mM glucose found in blood it runs at over 99% of Vmax; with Vmax = 100 µmol/min and Km = 2 mM, setting [S] = 2 mM gives exactly 50 µmol/min.', '/learn/enzymes/', 'Read: enzymes and activation energy'),
    q('What is the Michaelis-Menten equation?', 'V = Vmax [S] / (Km + [S]) gives the initial reaction rate at a substrate concentration [S]. At low [S] the rate rises almost in proportion to substrate; at high [S] the active sites are saturated and the rate levels off at Vmax. At [S] = 10 × Km the enzyme runs at 10/11 of Vmax, about 91%, and reaching 90% of Vmax needs [S] = 9 × Km, which is 18 mM when Km = 2 mM.', '/practice/', 'Practice enzyme questions'),
    q('What is the difference between competitive and noncompetitive inhibition?', 'A competitive inhibitor binds the active site, so it raises the apparent Km to Km(1 + [I]/Ki) but leaves Vmax unchanged: enough substrate can outcompete it. A noncompetitive inhibitor binds elsewhere and disables the enzyme whether or not substrate is bound, so it lowers the apparent Vmax to Vmax/(1 + [I]/Ki) and leaves Km unchanged. With [I] = Ki and [S] = Km, the competitive case doubles Km to 4 mM and drops the rate from 50 to 33.3 µmol/min, while the noncompetitive case halves Vmax and drops it to 25.', '/cells/lysosome/', 'See enzymes at work in a lysosome'),
  ],
  'dilution-calculator': [
    q('How do you use C1V1 = C2V2?', 'C₁ and V₁ are the concentration and volume of the stock you take; C₂ and V₂ are the concentration and volume you want to end up with. Rearrange for the unknown: to make 100 mL of 1 M from a 10 M stock, V₁ = C₂V₂ / C₁ = 1 × 100 / 10 = 10 mL of stock, then add 90 mL of water to reach 100 mL. Any concentration unit works (M, mM, mg/mL, %, ×) as long as C₁ and C₂ share it.', '/learn/lab-measurements/', 'Read: lab measurements and scale'),
    q('What is a serial dilution?', 'A serial dilution repeats the same dilution factor step after step, each tube made from the previous one. Three 1 : 10 steps from a 10 M stock give 1 M, 0.1 M, and 0.01 M, a total dilution of 1,000×; each step transfers 1 part into 9 parts of diluent. Serial dilutions are how you count bacteria on plates, build a standard curve, or find the lowest antibiotic dose that stops growth.', '/tools/bacterial-growth/', 'Count the bacteria you dilute'),
    q('What is the dilution factor?', 'The dilution factor is the final volume divided by the stock volume, V₂ / V₁, which equals C₁ / C₂. Taking 10 mL of stock up to 100 mL is a 10× or 1 : 10 dilution. For 500 mL of 70% ethanol from 95%, V₁ = 70 × 500 / 95 = 368.4 mL of stock plus 131.6 mL of water, a dilution factor of about 1.36×.', '/practice/', 'Practice lab calculations'),
  ],
  'magnification-calculator': [
    q('How do you calculate magnification?', 'Magnification = image size ÷ actual size, with both lengths in the same unit. A red blood cell 7.5 µm wide drawn 7.5 mm wide is magnified 7,500 µm ÷ 7.5 µm = 1,000×. Magnification has no units, and the same formula rearranges to actual size = image size ÷ magnification or image size = actual size × magnification.', '/learn/lab-measurements/', 'Read: lab measurements and scale'),
    q('How do you convert mm to µm?', 'Multiply millimeters by 1,000, because 1 mm = 1,000 µm (and 1 µm = 1,000 nm). A 20 mm drawing of a cell at 400× is 20,000 µm on paper, so the real cell is 20,000 ÷ 400 = 50 µm across. Forgetting the conversion is the most common exam error and gives an answer 1,000 times too large or too small.', '/tools/cell-size/', 'Compare cell sizes'),
    q('What is the total magnification of a microscope?', 'Multiply the eyepiece by the objective: a 10× eyepiece with a 40× objective gives 400×, and with a 100× oil-immersion objective gives 1,000×. Higher magnification shrinks the field of view, so at 400× a typical field is about 0.45 mm (450 µm) across and roughly nine 50 µm cells would fit in a row. Add a scale bar to a drawing by multiplying the real length by the magnification: 20 µm at 400× is an 8 mm bar.', '/practice/', 'Practice microscope questions'),
  ],
  'water-potential': [
    q('How do you calculate water potential?', 'Water potential Ψ = Ψs + Ψp, the sum of solute potential and pressure potential, measured in megapascals. Solute potential is Ψs = −iCRT, where i is the number of particles per formula unit, C is molarity, R = 0.00831 L·MPa/(mol·K), and T is the temperature in kelvin. For 0.1 M sucrose at 25 °C (298.15 K): Ψs = −1 × 0.1 × 0.00831 × 298.15 = −0.248 MPa, and with no pressure Ψ = −0.248 MPa.', '/learn/cell-transport/', 'Read: cell transport and osmosis'),
    q('Which way does water move in osmosis?', 'Water moves by osmosis from higher water potential to lower water potential, that is, toward the more negative number. A plant cell with Ψs = −0.743 MPa and turgor pressure Ψp = +0.5 MPa has Ψ = −0.243 MPa; placed in 0.5 M NaCl (Ψ = −2.478 MPa) it loses water to the solution and plasmolyzes. Pure water has Ψ = 0 MPa, so a red blood cell dropped into it gains water until it bursts.', '/cells/cell-membrane/', 'See the membrane water crosses'),
    q('What is the ionization constant i?', 'The ionization constant (van ’t Hoff factor) counts how many particles each formula unit releases in solution: 1 for sucrose and glucose, 2 for NaCl (Na⁺ and Cl⁻), 3 for CaCl₂. Because osmosis responds to particle numbers, 0.3 M NaCl behaves like 0.6 M dissolved particles: Ψs = −1.487 MPa at 25 °C, twice the −0.743 MPa of 0.3 M sucrose. The calculator assumes complete dissociation, which is close to true for dilute salt solutions.', '/practice/', 'Practice osmosis questions'),
  ],
  'bacterial-growth': [
    q('How do you calculate bacterial growth?', 'Bacteria divide by binary fission, so N = N₀ × 2ⁿ, where n = t / g is the number of generations in time t and g is the generation (doubling) time. Starting with 1,000 E. coli cells at g = 20 minutes, 4 hours (240 minutes) is 12 generations, giving 1,000 × 4,096 = 4.1 × 10⁶ cells. The graph uses a log scale, so this exponential growth appears as a straight line.', '/learn/prokaryotes-vs-eukaryotes/', 'Read: prokaryotes vs. eukaryotes'),
    q('How do you find the generation time?', 'Rearrange the growth equation: the number of generations is n = log₂(N / N₀), and the generation time is g = t / n. If 100 cells become 6,400 in 120 minutes, N / N₀ = 64 = 2⁶, so there were 6 generations and g = 120 / 6 = 20 minutes. The same numbers give a growth rate constant k = 3 generations per hour.', '/population-growth-calculator/', 'Model growth with a rate r'),
    q('Why does bacterial growth eventually stop?', 'Exponential growth only describes the log phase of a culture. If E. coli kept doubling every 20 minutes for two days, 144 generations would produce about 2 × 10⁴³ cells, thousands of times the mass of the Earth, which is clearly impossible. In a real flask nutrients run out and waste accumulates, so the curve levels off into the stationary phase and then falls in the death phase; slow growers such as Mycobacterium tuberculosis (g ≈ 20 hours) never get close.', '/practice/', 'Practice growth questions'),
  ],
  'energy-pyramid': [
    q('What is the 10% rule?', 'Only about 10% of the energy stored in one trophic level ends up stored in the biomass of the next; the other 90% is used for respiration, lost as heat, or left in uneaten and undigested material. If producers store 10,000 kJ, primary consumers get about 1,000 kJ, secondary consumers 100 kJ, and tertiary consumers 10 kJ, so 9,990 kJ (99.9%) never reaches the top. Real transfer efficiencies range from roughly 5% to 20%.', '/learn/energy-flow-in-ecosystems/', 'Read: energy flow in ecosystems'),
    q('Why are food chains usually only four or five levels long?', 'Because the energy runs out. At 10% efficiency a fifth trophic level receives 0.1⁴ = 0.01% of the producers’ energy: 1,000,000 kJ captured by plants leaves just 100 kJ for a quaternary consumer, too little to support a viable population of large predators. That is also why top predators are rare and why eating lower on the food chain feeds more people from the same land.', '/cells/chloroplast/', 'See where the energy enters'),
    q('Where does the lost energy go?', 'Most of it is released as heat when organisms respire to power movement, growth, and body temperature; the rest stays in parts that are never eaten, or leaves as feces and dead tissue that decomposers use. Energy is not destroyed, it is just no longer available to the next consumer, which is why an ecosystem needs a constant input of sunlight while nutrients such as carbon and nitrogen can be recycled.', '/learn/cellular-respiration/', 'Read: cellular respiration'),
  ],
  'chi-square-test': [
    q('How do you do a chi-square test for a Punnett square ratio?', 'Work out the expected count for each class from the ratio and the total, then add up (O − E)² / E across the classes. Mendel counted 705 purple and 224 white pea flowers, a total of 929; a 3 : 1 ratio predicts 696.75 and 232.25, so χ² = 0.098 + 0.293 = 0.391. That is below the critical value of 3.841 for 1 degree of freedom, so the data fit 3 : 1 and the hypothesis is not rejected.', '/learn/mendelian-inheritance/', 'Read: Mendelian inheritance'),
    q('What does the critical value mean?', 'The critical value is the largest χ² that chance alone would produce 95% of the time when the hypothesis is true (α = 0.05). It depends on the degrees of freedom: 3.841 for df = 1, 5.991 for df = 2, and 7.815 for df = 3. If your χ² is at or below it, the deviation is what sampling could produce, so you do not reject the ratio; the tool also reports the exact p-value, 0.532 for Mendel’s flower data.', '/punnett-square-calculator/', 'Predict the expected ratio'),
    q('What is a degree of freedom in a chi-square test?', 'Degrees of freedom equal the number of phenotype classes minus one, because once the total is fixed the last class count is not free to vary. A 3 : 1 or 1 : 1 test has df = 1, a 1 : 2 : 1 test has df = 2, and a 9 : 3 : 3 : 1 dihybrid test has df = 3. Mendel’s dihybrid counts of 315 : 108 : 101 : 32 give χ² = 0.47 against a critical value of 7.815 (p ≈ 0.93), an excellent fit; for reliable results every expected count should be at least 5.', '/practice/', 'Practice genetics statistics'),
  ],
  'predator-prey': [
    q('What are the Lotka-Volterra equations?', 'They are a pair of differential equations: prey change as dx/dt = αx − βxy and predators change as dy/dt = δxy − γy. Prey grow at rate α when left alone and are removed in proportion to how often they meet predators (βxy); predators gain from those meetings (δxy) and die at rate γ when food is scarce. The simulator integrates them with a fourth-order Runge–Kutta method and plots both populations over time.', '/learn/population-growth/', 'Read: population growth models'),
    q('Why do predator and prey populations cycle?', 'Predators lag behind their food. When prey are plentiful, predators breed and their numbers climb; heavy predation then drives prey down, predators starve and decline, and the prey recover to start the next cycle. With the default rates the populations orbit an equilibrium of x* = γ/δ = 30 prey and y* = α/β = 12 predators, with a period of about 15 time units, close to the small-swing estimate 2π/√(αγ) = 14.8. The lynx and snowshoe hare records kept by the Hudson’s Bay Company show roughly 10-year cycles of this kind.', '/population-growth-calculator/', 'Compare single-species growth'),
    q('Is the Lotka-Volterra model realistic?', 'It is a simplification: prey have unlimited food, predators eat nothing else, there is no carrying capacity, and the size of the cycle depends entirely on where the populations start. Real systems have refuges, alternative prey, and density limits that damp the swings, and small numbers can go extinct by chance. The model still captures the key insight that the two populations peak out of step and cycle around a fixed point.', '/practice/', 'Practice ecology questions'),
  ],
  nucleus: [
    q('What does the nucleus do?', 'The nucleus stores the cell’s genome, 46 chromosomes and about 2 m of DNA in a human cell, and controls which genes are transcribed into messenger RNA at any moment. Its nucleolus assembles ribosomal subunits, and its double membrane keeps DNA and transcription separate from the ribosomes in the cytoplasm, so mRNA can be capped and spliced before it is translated.', '/learn/dna-structure/', 'Read: DNA structure'),
    q('Do all cells have a nucleus?', 'No. Bacteria and archaea are prokaryotes: their circular DNA sits in a region called the nucleoid with no membrane around it. Among eukaryotic cells, mature mammalian red blood cells eject their nucleus to make room for hemoglobin, while skeletal muscle fibers fuse from many cells and carry hundreds of nuclei.', '/learn/prokaryotes-vs-eukaryotes/', 'Read: prokaryotes vs. eukaryotes'),
    q('How does mRNA get out of the nucleus?', 'Through nuclear pores, protein-lined channels about 120 nm wide that pierce the envelope; a typical nucleus has roughly 2,000 to 5,000 of them. A new transcript is capped, spliced, and given a poly-A tail first, then escorted through a pore into the cytoplasm, where free ribosomes or ribosomes on the rough ER translate it, often within minutes of the gene being switched on.', '/cells/ribosome/', 'Meet the ribosome'),
  ],
  mitochondrion: [
    q('What does the mitochondrion do?', 'Mitochondria carry out aerobic respiration: the Krebs cycle in the matrix strips electrons from pyruvate and loads them onto NADH and FADH₂, and the electron transport chain on the folded inner membrane (the cristae) uses them to pump protons and drive ATP synthase. In total, C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O yields about 30 to 32 ATP per glucose, compared with just 2 from glycolysis alone.', '/learn/cellular-respiration/', 'Read: cellular respiration'),
    q('Why do mitochondria have their own DNA?', 'Because they descend from free-living bacteria that were engulfed by an ancestral cell around two billion years ago, the endosymbiotic theory. Human mitochondrial DNA is a circle of 16,569 base pairs carrying 37 genes, translated on its own small bacterial-style ribosomes, and it is inherited almost entirely from the mother through the egg. The double membrane is another relic: the inner one is the old bacterial membrane.', '/cells/chloroplast/', 'Compare with the chloroplast'),
    q('Why do muscle cells have so many mitochondria?', 'Because they spend ATP faster than almost any other cell. Mitochondria fill about a third of a heart muscle cell’s volume, and a liver cell holds 1,000 to 2,000 of them. Each glucose gives only 2 ATP in the cytoplasm but about 28 more inside a mitochondrion, so a cell cut off from oxygen loses over 90% of its energy income within minutes, which is why a blocked coronary artery damages heart muscle so fast.', '/practice/', 'Practice cell questions'),
  ],
  chloroplast: [
    q('What does the chloroplast do?', 'Chloroplasts run photosynthesis: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. In the thylakoid membranes, chlorophyll captures light to split water, release oxygen, and charge ATP and NADPH; in the surrounding stroma, the Calvin cycle uses that energy and the enzyme RuBisCO to fix CO₂ into 3-carbon sugars. Surplus sugar is stored as starch grains during the day and used at night.', '/learn/photosynthesis/', 'Read: photosynthesis'),
    q('What is the difference between chloroplasts and mitochondria?', 'They run opposite reactions. Chloroplasts use light to build glucose from CO₂ and water and release O₂; mitochondria break glucose down with O₂ to make ATP and release CO₂ and water. Both have a double membrane, their own circular DNA, and small bacterial-style ribosomes, all relics of their bacterial ancestors, but chloroplasts add a third membrane system, the thylakoids, and occur only in plants, algae, and a few protists. Plant cells contain both organelles.', '/cells/mitochondrion/', 'Compare with the mitochondrion'),
    q('Do plants respire as well as photosynthesize?', 'Yes, every plant cell respires in its mitochondria day and night, because photosynthesis makes sugar but respiration is what turns it into usable ATP. In bright light photosynthesis outpaces respiration, so the leaf takes in CO₂ and gives off O₂ overall; in the dark only respiration continues and the gas exchange reverses. The light level at which the two balance is called the compensation point.', '/learn/cellular-respiration/', 'Read: cellular respiration'),
  ],
  ribosome: [
    q('What does a ribosome do?', 'A ribosome reads messenger RNA three bases at a time and joins the matching amino acids into a protein. Transfer RNAs carrying amino acids enter its A site, the growing chain is passed to them in the P site, and the empty tRNA leaves from the E site, at about 15 to 20 amino acids per second in bacteria and 5 to 6 in eukaryotes. The 146-amino-acid β-chain of hemoglobin takes a human ribosome roughly 30 seconds.', '/dna-transcription-translation/', 'Translate a sequence yourself'),
    q('Is a ribosome an organelle?', 'It depends on the definition. A ribosome has no membrane, so it is not a membrane-bound organelle; it is a molecular machine of ribosomal RNA and proteins about 20 to 30 nm across, and it occurs in every living cell, including bacteria. Eukaryotic ribosomes are 80S (a 60S and a 40S subunit) while prokaryotic ones are 70S (50S and 30S), a difference antibiotics such as tetracycline exploit to hit bacteria and spare us.', '/learn/prokaryotes-vs-eukaryotes/', 'Read: prokaryotes vs. eukaryotes'),
    q('What is the difference between free and bound ribosomes?', 'Free ribosomes float in the cytosol and make proteins that stay there, such as glycolysis enzymes. Bound ribosomes sit on the rough endoplasmic reticulum and feed their growing chains into the ER lumen, producing secreted proteins, membrane proteins, and lysosomal enzymes. They are the same ribosomes: a signal sequence at the start of the new protein decides whether the ribosome docks on the ER.', '/cells/endoplasmic-reticulum/', 'Follow proteins into the ER'),
  ],
  'endoplasmic-reticulum': [
    q('What does the endoplasmic reticulum do?', 'The ER is a network of membrane tubes and sacs continuous with the nuclear envelope. Rough ER, studded with ribosomes, threads new proteins into its lumen, folds them, and attaches sugar chains; smooth ER makes phospholipids, cholesterol, and steroid hormones, detoxifies drugs in liver cells, and stores calcium. It can account for more than half of all the membrane in a cell.', '/learn/transcription-and-translation/', 'Read: transcription and translation'),
    q('What is the difference between rough and smooth ER?', 'Rough ER has ribosomes on its surface and is arranged in flattened sacs; smooth ER has none and forms branching tubules. They are regions of one continuous membrane, not separate organelles, and the balance shifts with the cell’s job: an antibody-secreting plasma cell is packed with rough ER and releases about 2,000 antibodies per second, while liver cells exposed to drugs can double their smooth ER within days.', '/cells/ribosome/', 'Meet the ribosome'),
    q('Where do proteins go after the ER?', 'Vesicles bud from the ER and fuse with the cis face of the Golgi apparatus, where sugar chains are trimmed and rebuilt and sorting tags are added. At the trans face, new vesicles carry each protein to its destination: the cell membrane, a lysosome, or outside the cell. A typical protein takes about 20 minutes to cross a Golgi stack.', '/cells/golgi-apparatus/', 'Continue to the Golgi apparatus'),
  ],
  'golgi-apparatus': [
    q('What does the Golgi apparatus do?', 'The Golgi receives proteins and lipids from the ER, finishes them, and sorts them for delivery. Cargo enters at the cis face, moves through a stack of 4 to 8 flattened cisternae where enzymes rebuild its sugar chains and add sulfate or phosphate groups, and leaves from the trans face in vesicles bound for the cell membrane, lysosomes, or secretion. The mucus that lines your gut is up to 80% sugar by mass, nearly all of it attached in the Golgi.', '/learn/cell-transport/', 'Read: cell transport'),
    q('How does the Golgi know where to send a protein?', 'It reads molecular address tags. Lysosomal enzymes get a mannose-6-phosphate group that a receptor in the trans Golgi recognizes and diverts into lysosome-bound vesicles; proteins without a tag follow the default route to the cell surface. In I-cell disease the tagging enzyme is missing, so the digestive enzymes are secreted out of the cell and undigested material piles up inside.', '/cells/lysosome/', 'See where tagged enzymes end up'),
    q('Is the Golgi apparatus in plant cells?', 'Yes. Animal cells usually have one ribbon of linked stacks near the nucleus, but plant cells contain dozens to hundreds of separate stacks called dictyosomes. Besides finishing proteins, the plant Golgi builds the pectins and hemicelluloses of the cell wall and ships them out in vesicles; cellulose itself is spun by enzyme complexes in the cell membrane.', '/cells/endoplasmic-reticulum/', 'Go back a step to the ER'),
  ],
  lysosome: [
    q('What does a lysosome do?', 'A lysosome is a single-membrane sac holding about 50 acid hydrolases that digest proteins, lipids, carbohydrates, and nucleic acids. It breaks down material brought in by endocytosis or phagocytosis, recycles worn-out organelles through autophagy, and in white blood cells destroys engulfed bacteria; the products return to the cytosol as building blocks. Its surface is also where the mTORC1 complex decides whether the cell grows or recycles.', '/learn/enzymes/', 'Read: enzymes and activation energy'),
    q('Why are lysosomes acidic?', 'A proton pump (V-type ATPase) in the membrane holds the interior at pH 4.5 to 5.0, while the cytosol sits near pH 7.2, a 100- to 500-fold difference in H⁺ concentration. The hydrolases work best at that low pH and are nearly inactive at neutral pH, so if a lysosome leaks its enzymes do little damage. That is why lysosomes are not the “suicide sacs” of old textbooks; programmed cell death is run by caspase enzymes instead.', '/cells/cell-membrane/', 'See the membrane that holds the gradient'),
    q('Do plant cells have lysosomes?', 'Rarely, and it is one of the classic animal-versus-plant differences. In plants the large central vacuole is acidic and holds hydrolytic enzymes, so it does the digesting; some plant and fungal cells have smaller lytic vacuoles that play the same part. Animal cells hold tens to a few hundred lysosomes, and macrophages that eat bacteria for a living carry far more.', '/cells/', 'Compare all eight organelles'),
  ],
  'cell-membrane': [
    q('What is the cell membrane made of?', 'A phospholipid bilayer about 7 to 8 nm thick, with the phosphate heads facing the water on either side and the fatty-acid tails buried in the middle, plus cholesterol and a mosaic of embedded proteins. By mass a typical animal cell membrane is roughly half lipid and half protein, about 50 lipid molecules per protein. The fluid mosaic model, proposed by Singer and Nicolson in 1972, captures how the lipids and proteins drift sideways within the sheet.', '/learn/cell-transport/', 'Read: cell transport and osmosis'),
    q('What can pass through the cell membrane?', 'Small nonpolar molecules such as O₂, CO₂, and steroid hormones dissolve through the lipid bilayer directly, and water crosses slowly on its own or quickly through aquaporin channels. Ions and sugars cannot cross the oily interior, so they need channel or carrier proteins, and the Na⁺/K⁺ pump uses one ATP to push 3 Na⁺ out and 2 K⁺ in against their gradients. Polarity matters more than size: a tiny Na⁺ ion is blocked while a much larger steroid slips through.', '/tools/water-potential/', 'Calculate which way water moves'),
    q('What is the difference between the cell membrane and the cell wall?', 'Every cell has a membrane, a thin selective bilayer that controls what enters and leaves. A cell wall is an extra rigid layer outside the membrane found in plants (cellulose), fungi (chitin), and bacteria (peptidoglycan) but never in animal cells; it is porous to water and small molecules, so it does not choose what gets in. Instead it resists swelling, letting a plant cell build up turgor pressure of around 0.5 MPa and stay firm rather than burst.', '/practice/', 'Practice cell questions'),
  ],
  'printable-diagrams': [
    q('What printable diagrams are available?', 'Five printables: an animal cell to label, a plant cell to label, a blank monohybrid Punnett square (2 × 2), a blank dihybrid Punnett square (4 × 4), and a blank three-generation pedigree chart. Each is drawn as an SVG sized for an A4 or US Letter portrait page, and a single toggle switches between the blank version for students and the labeled answer key. Between them, the two cell diagrams label all eight organelles from the cell atlas.', '/cells/', 'Read about each organelle first'),
    q('How do I print a diagram or save it as a PDF?', 'Press the Print / save as PDF button and your browser opens its print dialog; choose a printer, or pick “Save as PDF” as the destination to keep a copy. Use portrait orientation, choose the same paper size you picked on the page (A4 or US Letter), and print at 100% scale rather than “fit to page” so the 20 mm line at the foot of the sheet measures 20 mm with a ruler. Because the diagram is a vector SVG, lines and labels stay crisp at any size, and the Download SVG button gives you a file you can edit or drop into slides.', '/worksheets/', 'Build a question sheet to go with it'),
    q('How do I use a blank Punnett square?', 'Write one parent’s gametes along the top and the other parent’s down the left side, one allele (or one combination) per box. For a monohybrid cross such as Aa × Aa the 2 × 2 grid gives AA, Aa, Aa, aa; for a dihybrid cross such as AaBb × AaBb each parent contributes four gametes (AB, Ab, aB, ab), so the 4 × 4 grid has 16 boxes and yields the 9 : 3 : 3 : 1 ratio. Check your filled-in grid against the calculator.', '/punnett-square-calculator/', 'Check your answers with the calculator'),
  ],
};
