// Concept notes for /learn/ and /learn/<slug>/. Sixteen lessons in the site-map order fixed by the spec.
// Each entry: slug, title (≤ 37 chars so "— Key Idea & Worked Example" fits a 65-char SEO title), subtitle, formula (key equation or
// one-line principle), body (3–4 sentences), example (worked numbers), pitfall (a real misconception and its correction),
// href + cta (the tool that makes the idea move), icon (one character), keywords, related (two other lesson slugs).
export const lessons = [
  {
    slug: 'cell-theory',
    title: 'Cell theory',
    subtitle: 'Three statements that every living thing obeys.',
    formula: 'Omnis cellula e cellula — every cell comes from a pre-existing cell',
    body: 'Cell theory, assembled by Schleiden and Schwann in 1838–39 and completed by Virchow in 1855, makes three claims: all living organisms are made of one or more cells, the cell is the smallest unit that shows every property of life, and new cells arise only when existing cells divide. The modern version adds that cells pass hereditary information to their daughters as DNA, that energy flow (metabolism) happens inside cells, and that all cells share the same basic chemistry of membranes, proteins, and nucleic acids. The third statement rules out spontaneous generation, which Pasteur’s swan-neck flask experiments of 1859–61 finally put to rest. Everything from a 0.3 µm Mycoplasma to a blue whale is built on this one plan.',
    example: 'An adult human body contains roughly 30 trillion (3 × 10¹³) human cells, every one descended from a single fertilized egg by repeated mitosis. Because each division doubles the count, reaching 3 × 10¹³ takes at least 45 successive doublings, since 2⁴⁵ ≈ 3.5 × 10¹³; in reality far more divisions occur, because cells also die and are replaced. Your red blood cells alone are renewed at about 2–3 million per second.',
    pitfall: 'Viruses are not an exception to cell theory — they are not cells at all. A virus has no cytoplasm, no ribosomes, and no metabolism of its own, so it cannot grow or divide; it only multiplies by hijacking a living host cell. Likewise, "all cells are microscopic" is false: a chicken egg yolk is a single cell, and some human neurons run more than a meter from the spinal cord to the toe.',
    href: '/cells/',
    cta: 'Explore the cell atlas',
    icon: '◉',
    keywords: 'cell theory schleiden schwann virchow all cells come from cells',
    related: ['prokaryotes-vs-eukaryotes', 'surface-area-to-volume'],
  },
  {
    slug: 'prokaryotes-vs-eukaryotes',
    title: 'Prokaryotes vs. eukaryotes',
    subtitle: 'Two cell plans: one with a nucleus, one without.',
    formula: 'Prokaryote: no nucleus, 70S ribosomes · Eukaryote: nucleus, 80S ribosomes',
    body: 'Prokaryotes (bacteria and archaea) are typically 1–10 µm across and keep a single circular chromosome in a nucleoid region with no membrane around it; they have no membrane-bound organelles, small 70S ribosomes built from 50S and 30S subunits, often extra DNA rings called plasmids, and a cell wall (peptidoglycan in bacteria). They reproduce asexually by binary fission: the chromosome is copied, the cell elongates, and a septum pinches it into two identical cells. Eukaryotes (animals, plants, fungi, and protists) are usually 10–100 µm, store linear chromosomes wound around histones inside a nuclear envelope, contain mitochondria, endoplasmic reticulum, and Golgi, use larger 80S ribosomes (60S + 40S), and divide by mitosis. Tellingly, mitochondria and chloroplasts carry their own circular DNA and 70S ribosomes — evidence that they descend from engulfed bacteria (endosymbiosis).',
    example: 'E. coli in a rich medium at 37 °C divides every 20 minutes. Starting from one cell, 2 hours means 6 doublings and 2⁶ = 64 cells; 8 hours means 24 doublings and 2²⁴ = 16,777,216 cells. The ribosome difference is medically useful: streptomycin and tetracycline bind the bacterial 30S subunit, so they stop bacterial protein synthesis but leave your own 80S cytoplasmic ribosomes alone.',
    pitfall: 'The S in 70S and 80S stands for Svedberg units, a measure of how fast a particle sediments in a centrifuge, not its mass — which is why the subunits do not add up (50S + 30S = 70S, 60S + 40S = 80S). And "no organelles" does not mean "nothing inside": prokaryotes are packed with ribosomes and a simple cytoskeleton, and cyanobacteria even have internal photosynthetic membranes; what they lack is membrane-bound organelles.',
    href: '/tools/bacterial-growth/',
    cta: 'Model bacterial growth',
    icon: '◌',
    keywords: 'prokaryotic eukaryotic cell differences binary fission 70S 80S ribosomes nucleoid',
    related: ['cell-theory', 'cellular-respiration'],
  },
  {
    slug: 'cell-transport',
    title: 'Cell transport & osmosis',
    subtitle: 'How water, ions, and molecules cross a membrane.',
    formula: 'Ψ = Ψs + Ψp · water moves from higher Ψ to lower Ψ',
    body: 'The phospholipid bilayer lets small nonpolar molecules such as O₂ and CO₂ slip through by simple diffusion, down their concentration gradient, at no energy cost. Ions and polar molecules such as glucose need help: facilitated diffusion moves them through channel or carrier proteins, still passively and still down the gradient. Osmosis is the diffusion of water across a selectively permeable membrane from higher water potential (Ψ) to lower; pure water has Ψ = 0, dissolved solutes make it negative (the solute potential Ψs), and pressure from a cell wall pushes it back up (the pressure potential Ψp). Active transport moves substances against their gradient using ATP — the sodium–potassium pump, for example, exports 3 Na⁺ and imports 2 K⁺ for every ATP it splits — while endocytosis and exocytosis move bulk cargo in vesicles.',
    example: 'A plant cell has Ψs = −0.8 MPa and Ψp = +0.3 MPa, so its water potential is −0.8 + 0.3 = −0.5 MPa. Drop it into a sucrose solution with Ψ = −0.2 MPa: water moves from −0.2 (higher) to −0.5 (lower), so it enters the cell. The cell swells until the wall pushes Ψp up to +0.6 MPa, giving −0.8 + 0.6 = −0.2 MPa, and net flow stops. For reference, 0.1 M sucrose at 25 °C has Ψs = −iCRT = −1 × 0.1 × 0.00831 × 298 ≈ −0.25 MPa.',
    pitfall: 'Water does not move "toward the higher concentration" — that phrase describes the solute. Water moves toward the more concentrated solution, which is the side with the lower (more negative) water potential. Remember that every solution has a negative Ψ, so a cell at −0.5 MPa loses water to a beaker at −0.9 MPa even though both numbers look small.',
    href: '/tools/water-potential/',
    cta: 'Calculate water potential',
    icon: '⇄',
    keywords: 'osmosis diffusion facilitated diffusion active transport water potential membrane',
    related: ['surface-area-to-volume', 'prokaryotes-vs-eukaryotes'],
  },
  {
    slug: 'dna-structure',
    title: 'DNA structure',
    subtitle: 'A twisted ladder built from four bases.',
    formula: 'A pairs with T (2 hydrogen bonds) · G pairs with C (3 hydrogen bonds)',
    body: 'DNA is a polymer of nucleotides, each made of a deoxyribose sugar, a phosphate group, and one of four nitrogenous bases: adenine, thymine, guanine, or cytosine. Phosphodiester bonds link sugar to phosphate along each backbone, and the two strands run antiparallel — one 5′→3′, the other 3′→5′ — twisting into a right-handed double helix about 2 nm wide with roughly 10 base pairs per 3.4 nm turn, as Watson and Crick showed in 1953 using Franklin’s X-ray images. Bases pair across the middle by hydrogen bonds, always a two-ring purine with a one-ring pyrimidine so that every rung is the same width: A with T by two hydrogen bonds, G with C by three. That complementarity explains Chargaff’s rules (%A = %T and %G = %C) and lets either strand serve as a template for copying the other.',
    example: 'A DNA sample is 30% adenine. By Chargaff’s rules thymine is also 30%, so A + T = 60% and the remaining 40% is split equally: 20% G and 20% C. To write the complement of 5′-ATGGCA-3′, swap A↔T and G↔C and reverse the direction: 3′-TACCGT-5′. Scale check: the diploid human genome holds about 6.4 billion base pairs; at 0.34 nm per pair that is roughly 2 m of DNA folded into a nucleus about 6 µm across.',
    pitfall: 'The two strands are held together by hydrogen bonds, not covalent bonds; the covalent phosphodiester bonds run along each backbone. That is why heating DNA to about 95 °C in PCR separates the strands without breaking either one, and why G–C-rich DNA, with three hydrogen bonds per pair, needs a higher temperature to melt. A related slip: uracil belongs to RNA — DNA uses thymine.',
    href: '/dna-transcription-translation/',
    cta: 'Transcribe and translate a sequence',
    icon: '⌇',
    keywords: 'dna double helix nucleotide base pairing chargaff antiparallel hydrogen bonds',
    related: ['transcription-and-translation', 'mitosis-and-meiosis'],
  },
  {
    slug: 'transcription-and-translation',
    title: 'Transcription & translation',
    subtitle: 'From a gene to a working protein, in two steps.',
    formula: 'DNA → mRNA (transcription) → protein (translation)',
    body: 'In transcription, RNA polymerase binds a promoter, unzips the DNA, and builds a single strand of messenger RNA complementary to the template strand, working 5′→3′ and using uracil in place of thymine. In eukaryotes the pre-mRNA receives a 5′ cap and a poly-A tail and has its introns spliced out before it leaves the nucleus. In translation, a ribosome reads the mRNA three bases at a time; each codon is matched by a transfer RNA whose anticodon is complementary and which carries one specific amino acid, and the ribosome joins those amino acids with peptide bonds. Translation begins at the start codon AUG (methionine) and ends at a stop codon — UAA, UAG, or UGA — which has no matching tRNA and releases the finished polypeptide.',
    example: 'Template strand 3′-TAC GGA CTC ATT-5′ is transcribed into mRNA 5′-AUG CCU GAG UAA-3′ (T→A, A→U, C→G, G→C). Reading the codons: AUG = methionine, CCU = proline, GAG = glutamic acid, UAA = stop. Twelve nucleotides therefore encode a three-amino-acid peptide, Met–Pro–Glu. The coding (sense) strand, 5′-ATG CCT GAG TAA-3′, matches the mRNA letter for letter except for T in place of U.',
    pitfall: 'mRNA is built from the template (antisense) strand, so it is complementary to that strand and identical to the coding strand — students who transcribe the coding strand get the wrong message. Also, the code is degenerate, not ambiguous: 61 sense codons specify 20 amino acids, so leucine has six codons while methionine and tryptophan have one each, but no codon ever means two different things.',
    href: '/dna-transcription-translation/',
    cta: 'Translate a DNA sequence',
    icon: '→',
    keywords: 'transcription translation mrna codon anticodon ribosome trna start codon stop codon',
    related: ['dna-structure', 'enzymes'],
  },
  {
    slug: 'mitosis-and-meiosis',
    title: 'Mitosis & meiosis',
    subtitle: 'Copy a cell, or halve its chromosome set.',
    formula: 'Mitosis: 2n → two 2n cells · Meiosis: 2n → four n cells',
    body: 'Both divisions follow an interphase in which DNA is replicated (S phase), so each chromosome enters division as two identical sister chromatids joined at a centromere. Mitosis is a single division — prophase, metaphase, anaphase, telophase (PMAT) — that pulls sister chromatids apart and produces two genetically identical diploid (2n) cells for growth, repair, and asexual reproduction. Meiosis is two divisions in a row that produce four genetically different haploid (n) gametes: in prophase I homologous chromosomes pair up and swap segments (crossing over), in metaphase I each homologous pair lines up in a random orientation (independent assortment), anaphase I separates the homologs, and anaphase II finally separates the sister chromatids. In humans that takes 46 chromosomes down to 23, and fertilization restores 46.',
    example: 'A human cell with 2n = 46 replicates its DNA and enters division with 46 chromosomes made of 92 chromatids. Mitosis gives two cells with 46 chromosomes each. Meiosis I gives two cells with 23 chromosomes (each still two chromatids), and meiosis II gives four cells with 23 single-chromatid chromosomes. Independent assortment alone allows 2²³ = 8,388,608 different chromosome combinations in one gamete, before crossing over adds more.',
    pitfall: 'Chromosome number does not double in S phase — DNA content doubles, but a chromosome with two chromatids still counts as one chromosome, so count centromeres, not arms. Likewise, it is anaphase I, where homologous pairs separate, that halves the chromosome number (the reductional division); anaphase II separates sister chromatids exactly as mitosis does, and the number stays at n.',
    href: '/practice/',
    cta: 'Practice cell division questions',
    icon: '✕',
    keywords: 'mitosis meiosis phases pmat haploid diploid crossing over independent assortment',
    related: ['dna-structure', 'mendelian-inheritance'],
  },
  {
    slug: 'mendelian-inheritance',
    title: 'Mendelian inheritance',
    subtitle: 'Alleles, dominance, and predictable ratios.',
    formula: 'Aa × Aa → 1 AA : 2 Aa : 1 aa → 3 dominant : 1 recessive',
    body: 'A gene can come in different versions called alleles, and a diploid organism carries two of them, one from each parent; that pair is its genotype, and the trait it shows is its phenotype. A dominant allele masks a recessive one in the heterozygote, so AA and Aa look the same and only aa shows the recessive trait. Mendel’s law of segregation says the two alleles separate into different gametes (in meiosis I), and his law of independent assortment says alleles of genes on different chromosomes are sorted independently — which is why a dihybrid cross AaBb × AaBb yields a 9 : 3 : 3 : 1 ratio. A Punnett square simply lists every gamete combination to turn those laws into predicted ratios, and a test cross against a homozygous recessive partner reveals whether a dominant-looking individual is AA (all offspring dominant) or Aa (a 1 : 1 split).',
    example: 'In pea plants tall (T) is dominant over dwarf (t). Cross two heterozygotes, Tt × Tt: each parent makes T and t gametes, the square fills with TT, Tt, Tt, and tt, and the expected ratios are 1 : 2 : 1 by genotype and 3 tall : 1 dwarf by phenotype — 300 tall and 100 dwarf in 400 offspring. Mendel’s own count was 787 tall to 277 dwarf, a ratio of 2.84 : 1. A test cross Tt × tt would give half tall and half dwarf, whereas TT × tt gives all tall.',
    pitfall: 'Dominant does not mean common, strong, or better — it only describes which phenotype appears in the heterozygote. Huntington’s disease and polydactyly are dominant yet rare, while blood group O, a recessive trait, is the most common group in many populations. And Mendelian ratios are probabilities: four children of Aa parents are not guaranteed to come out three to one.',
    href: '/punnett-square-calculator/',
    cta: 'Build a Punnett square',
    icon: '⊞',
    keywords: 'mendel alleles dominant recessive genotype phenotype punnett square 3:1 9:3:3:1 test cross',
    related: ['mitosis-and-meiosis', 'hardy-weinberg-principle'],
  },
  {
    slug: 'hardy-weinberg-principle',
    title: 'The Hardy-Weinberg principle',
    subtitle: 'The baseline of a population that isn’t evolving.',
    formula: 'p + q = 1 · p² + 2pq + q² = 1',
    body: 'For a gene with two alleles, let p be the frequency of the dominant allele A and q the frequency of the recessive allele a, so p + q = 1. Hardy and Weinberg showed independently in 1908 that if a population is very large, mates at random, and experiences no mutation, no migration (gene flow), and no natural selection, then allele frequencies stay constant from generation to generation and the genotypes settle at p² (AA), 2pq (Aa), and q² (aa). Because heterozygotes hide inside the dominant phenotype, the recessive phenotype frequency, q², is the usual starting point for any calculation. A population whose genotype frequencies drift away from these values is telling you that at least one of the five assumptions is being broken — in other words, that it is evolving.',
    example: 'Cystic fibrosis, a recessive condition, affects about 1 in 2,500 people of European ancestry, so q² = 0.0004. Taking the square root, q = 0.02, and p = 1 − 0.02 = 0.98. The carrier frequency is 2pq = 2 × 0.98 × 0.02 = 0.0392, roughly 1 person in 25 — which is why a disease that is rare can still be carried by about 4% of the population.',
    pitfall: 'If 16% of a population shows the recessive trait, q is not 0.16: that figure is q², so q = √0.16 = 0.4, p = 0.6, and heterozygotes make up 2 × 0.6 × 0.4 = 48%. Nor must the dominant phenotype be the common one: with q = 0.8, fully 64% of individuals are aa even though A is dominant. Dominance describes masking, not frequency.',
    href: '/hardy-weinberg-calculator/',
    cta: 'Run the Hardy-Weinberg numbers',
    icon: '∑',
    keywords: 'hardy weinberg equilibrium allele frequency p2 2pq q2 five assumptions carrier frequency',
    related: ['mendelian-inheritance', 'natural-selection'],
  },
  {
    slug: 'natural-selection',
    title: 'Natural selection',
    subtitle: 'Variation, heredity, and who leaves more offspring.',
    formula: 'Variation + heritability + differential reproduction → adaptation',
    body: 'Darwin’s mechanism needs three ingredients: individuals in a population vary (thanks to mutation and the reshuffling of meiosis), some of that variation is heritable, and in a given environment individuals with certain heritable traits survive and reproduce more than others. Fitness means reproductive success — how many offspring carry your alleles — not strength or size. Over generations the alleles behind the favored traits become more common, and that change in allele frequencies is evolution; depending on which phenotypes are favored, selection is called directional, stabilizing, or disruptive. Individuals do not evolve — an animal cannot change its own genes to suit its needs — populations do, because selection changes which individuals leave descendants.',
    example: 'The peppered moth is the classic case. The dark (melanic) form was first recorded near Manchester in 1848; as soot blackened tree trunks and killed pale lichens, pale moths became easy prey for birds, and by 1895 about 98% of Manchester’s moths were dark. After the Clean Air Act of 1956 the trees lightened and the pale form rebounded. Antibiotic resistance runs the same way on a faster clock: in a culture of 10⁹ bacteria, a resistance mutation carried by 1 cell in 10⁸ means about 10 resistant cells are already present; add the antibiotic, and those 10 are the only ones that keep dividing every 20–30 minutes.',
    pitfall: 'Bacteria do not "become resistant because they need to." Resistance mutations arise at random before the drug appears, and the antibiotic merely selects among existing variants — Joshua and Esther Lederberg showed this in 1952 by replica plating, finding streptomycin-resistant colonies on plates that had never met streptomycin. "Survival of the fittest" therefore does not mean the strongest survive; it means the individuals that reproduce most pass on the most alleles.',
    href: '/hardy-weinberg-calculator/',
    cta: 'See selection change allele frequencies',
    icon: '⇡',
    keywords: 'natural selection darwin fitness variation peppered moth antibiotic resistance populations evolve',
    related: ['hardy-weinberg-principle', 'population-growth'],
  },
  {
    slug: 'enzymes',
    title: 'Enzymes & activation energy',
    subtitle: 'Biological catalysts that lower the energy hill.',
    formula: 'v = Vmax [S] / (Km + [S])',
    body: 'Enzymes are proteins (plus a few RNA ribozymes) that speed up reactions by lowering the activation energy — the energy barrier reactants must climb — without being used up and without changing the final equilibrium. A substrate binds a precisely shaped pocket called the active site; in the induced-fit model the site closes around the substrate and strains its bonds, which is why each enzyme works on only one substrate or family of substrates. Rate rises with substrate concentration until every active site is busy, giving the Michaelis–Menten curve: Vmax is the ceiling, and Km is the substrate concentration at half of Vmax, so a low Km signals tight binding. Every enzyme has an optimum temperature and pH; too much heat or the wrong pH breaks the hydrogen and ionic bonds holding the protein’s shape, the active site distorts, and the enzyme denatures.',
    example: 'An enzyme has Vmax = 100 µmol/min and Km = 2 mM. At [S] = 2 mM, v = 100 × 2 / (2 + 2) = 50 µmol/min, half of Vmax by definition. At 8 mM, v = 100 × 8 / 10 = 80 µmol/min; at 18 mM, v = 100 × 18 / 20 = 90 µmol/min. Quadrupling the substrate from 2 to 8 mM raised the rate from 50% to only 80% of Vmax. A competitive inhibitor would raise the apparent Km but leave Vmax alone; a non-competitive inhibitor would lower Vmax and leave Km alone.',
    pitfall: 'Enzymes are not "killed" by heat — they were never alive. They are denatured: the tertiary structure unfolds so the active site no longer fits its substrate, and for most enzymes that is permanent. Cold does the opposite of denaturing; it just slows molecular collisions, which is why food keeps in a refrigerator and why the enzyme works again when warmed. Human enzymes generally peak near 37 °C, but pepsin prefers pH 2 in the stomach while trypsin prefers pH 8 in the small intestine.',
    href: '/tools/enzyme-kinetics/',
    cta: 'Plot a Michaelis-Menten curve',
    icon: '⚗',
    keywords: 'enzyme active site induced fit activation energy km vmax michaelis menten denaturation',
    related: ['cellular-respiration', 'transcription-and-translation'],
  },
  {
    slug: 'photosynthesis',
    title: 'Photosynthesis',
    subtitle: 'Light, water, and CO₂ become sugar and oxygen.',
    formula: '6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂',
    body: 'In the light-dependent reactions, chlorophyll in the thylakoid membranes absorbs light; photosystem II splits water (photolysis), releasing O₂ as a by-product and passing electrons down an electron transport chain that pumps H⁺ into the thylakoid space so ATP synthase can make ATP, while photosystem I hands the electrons on to reduce NADP⁺ to NADPH. In the light-independent reactions of the Calvin cycle, in the stroma, the enzyme RuBisCO fixes CO₂ onto the five-carbon sugar RuBP to give two molecules of three-carbon 3-phosphoglycerate, which ATP and NADPH reduce to triose phosphate (G3P); most G3P is recycled to regenerate RuBP and the rest builds glucose, sucrose, starch, and cellulose. Because these are enzyme-driven steps, the overall rate is set by whichever factor is in shortest supply — light intensity, CO₂ concentration, or temperature — the law of limiting factors. Only about 1–2% of the sunlight hitting a leaf ends up stored in sugar.',
    example: 'Making one glucose (six carbons) takes six turns of the Calvin cycle: 6 CO₂ are fixed, 18 ATP and 12 NADPH are consumed, and 12 G3P are produced, of which 2 leave to form glucose and 10 are rearranged back into 6 RuBP. Those 12 NADPH require 24 electrons, which come from splitting 12 H₂O — releasing exactly the 6 O₂ in the equation. Van Helmont’s 17th-century willow makes the scale vivid: it gained about 74 kg in five years while its pot of soil lost only 57 g, because nearly all of the new mass came from CO₂ in the air.',
    pitfall: 'The oxygen a plant releases comes from water, not from carbon dioxide — Ruben and Kamen showed this in 1941 by giving algae water labeled with heavy oxygen (¹⁸O) and finding the label in the O₂ gas. Also, plants do not "photosynthesize by day and respire by night": every plant cell respires around the clock, and in daylight photosynthesis simply outpaces respiration, so the leaf is a net oxygen producer.',
    href: '/cells/chloroplast/',
    cta: 'Look inside a chloroplast',
    icon: '☀',
    keywords: 'photosynthesis equation light dependent reactions calvin cycle thylakoid stroma limiting factors',
    related: ['cellular-respiration', 'energy-flow-in-ecosystems'],
  },
  {
    slug: 'cellular-respiration',
    title: 'Cellular respiration',
    subtitle: 'Glucose comes apart, and ATP captures the energy.',
    formula: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ~30–32 ATP',
    body: 'Glycolysis, in the cytoplasm, splits one six-carbon glucose into two three-carbon pyruvate molecules with a net gain of 2 ATP and 2 NADH — no oxygen required. When oxygen is available, pyruvate enters the mitochondrial matrix, loses CO₂ to become acetyl-CoA, and feeds the Krebs (citric acid) cycle, which per glucose releases 4 CO₂ and loads electrons onto 6 NADH and 2 FADH₂ while making 2 ATP directly. Those carriers deliver their electrons to the electron transport chain on the folded inner membrane (cristae); the chain pumps H⁺ into the intermembrane space, oxygen accepts the spent electrons to form water, and H⁺ flowing back through ATP synthase makes the bulk of the roughly 30–32 ATP per glucose (chemiosmosis). Without oxygen, cells fall back on fermentation — lactate in muscle, ethanol and CO₂ in yeast — which only regenerates the NAD⁺ that glycolysis needs, so the yield stays at 2 ATP.',
    example: 'Tally one glucose: glycolysis 2 ATP + 2 NADH; pyruvate to acetyl-CoA 2 NADH; Krebs cycle 2 ATP + 6 NADH + 2 FADH₂. In the electron transport chain each NADH is worth about 2.5 ATP and each FADH₂ about 1.5, so 10 × 2.5 + 2 × 1.5 = 28 ATP, plus the 4 made directly, gives 32 ATP (30 if the two cytoplasmic NADH enter the mitochondrion by the cheaper glycerol-phosphate shuttle). Glucose holds about 2,870 kJ/mol and each ATP stores about 30.5 kJ/mol, so 32 × 30.5 / 2,870 ≈ 34% of the energy is captured; the rest leaves as heat.',
    pitfall: 'Respiration is not breathing. Breathing (ventilation) moves air, and gas exchange swaps O₂ for CO₂ in the lungs; cellular respiration is the chemical breakdown of glucose that happens in every living cell — including every plant cell, day and night. Older textbooks quote 36–38 ATP per glucose; that was a theoretical maximum that ignored the cost of moving ATP and pyruvate across mitochondrial membranes, and the modern measured figure is about 30–32.',
    href: '/cells/mitochondrion/',
    cta: 'Look inside a mitochondrion',
    icon: '⚡',
    keywords: 'cellular respiration glycolysis krebs cycle electron transport chain atp yield fermentation',
    related: ['photosynthesis', 'enzymes'],
  },
  {
    slug: 'population-growth',
    title: 'Population growth models',
    subtitle: 'Exponential with no limits, logistic with them.',
    formula: 'dN/dt = rN · dN/dt = rN(1 − N/K)',
    body: 'When resources are unlimited a population grows exponentially: the per-capita growth rate r (births minus deaths per individual per unit time) stays constant, N(t) = N₀eʳᵗ, and the doubling time is ln 2 / r ≈ 0.693 / r, giving a J-shaped curve. Real populations run into limits, so the logistic model multiplies rN by (1 − N/K), where K is the carrying capacity the environment can support; growth is fastest at N = K/2, slows as N approaches K, and the curve becomes S-shaped. Density-dependent factors — food, disease, predation, competition — are what set K, while density-independent factors such as drought or frost strike regardless of how crowded the population is. Species built for rapid growth (r-selected, like insects) and species that hold steady near K (K-selected, like elephants) ride these curves in different ways.',
    example: 'Fifty rabbits grow at r = 0.1 per month. Doubling time is 0.693 / 0.1 ≈ 6.9 months, and after 20 months N = 50 × e² ≈ 50 × 7.39 ≈ 369 rabbits. Now give the field a carrying capacity K = 1,000: at N = 50, growth is 0.1 × 50 × (1 − 0.05) ≈ 4.75 rabbits per month; at N = 500 it peaks at 0.1 × 500 × 0.5 = 25 per month; at N = 900 it has fallen to 0.1 × 900 × 0.1 = 9 per month. The rule of 70 gives the same doubling estimate quickly: 70 / (10% per month) = 7 months.',
    pitfall: 'A population does not glide up to K and sit there. Real populations overshoot, crash, and oscillate, and K itself shifts with the seasons. The reindeer released on St. Matthew Island, Alaska, are the cautionary tale: 29 animals in 1944 became about 6,000 by 1963, then ate out the lichen and collapsed to 42 by 1966. Note too that the doubling time in exponential growth is constant — it depends on r, not on how big the population already is.',
    href: '/population-growth-calculator/',
    cta: 'Model exponential and logistic growth',
    icon: '↗',
    keywords: 'population growth exponential logistic carrying capacity doubling time r K rule of 70',
    related: ['natural-selection', 'energy-flow-in-ecosystems'],
  },
  {
    slug: 'energy-flow-in-ecosystems',
    title: 'Energy flow in ecosystems',
    subtitle: 'Why so little sunlight reaches the top predator.',
    formula: 'Energy at trophic level n + 1 ≈ 10% of energy at level n',
    body: 'Producers — plants, algae, and cyanobacteria — capture roughly 1% of the sunlight that reaches them and store it as chemical energy in their tissues. That energy passes along the food chain to primary consumers (herbivores), secondary consumers, and tertiary consumers, but at each step only about 10% is built into new biomass at the next level; the rest is lost as heat from respiration, in undigested feces, and in parts that are never eaten. Because of this trophic efficiency of roughly 5–20%, a pyramid of energy is always upright, whereas a pyramid of numbers can be inverted (one oak tree feeding thousands of caterpillars) and a pyramid of biomass can be inverted in the sea, where fast-breeding phytoplankton support a heavier standing crop of zooplankton. Energy dwindles so quickly that food chains rarely run past four or five links, and unlike carbon, nitrogen, and water, energy flows through an ecosystem once and never cycles back.',
    example: 'A meadow’s grasses store 10,000 kJ per square meter per year. Grasshoppers get about 1,000 kJ, the frogs that eat them 100 kJ, the snakes 10 kJ, and a hawk at the fifth level just 1 kJ — one ten-thousandth of what the plants captured, which is why top predators need large territories. The same arithmetic applies to farming: a hectare of grain feeds about ten times as many people when eaten directly as it does after being fed to cattle first.',
    pitfall: 'Energy is not recycled — decomposers return nutrients to the soil, but the energy in every organism ultimately leaves as heat, and only a fresh supply of sunlight keeps the system running. And 10% is a rule of thumb, not a law: mammals and birds, which burn most of their food keeping warm, convert only 1–3% of what they assimilate into new tissue, while insects can manage around 40%.',
    href: '/tools/energy-pyramid/',
    cta: 'Build an energy pyramid',
    icon: '▲',
    keywords: 'energy flow trophic levels 10 percent rule energy pyramid pyramid of numbers food chain length',
    related: ['photosynthesis', 'population-growth'],
  },
  {
    slug: 'surface-area-to-volume',
    title: 'Surface area to volume ratio',
    subtitle: 'The geometry that keeps cells small.',
    formula: 'Cube: SA : V = 6s² : s³ = 6 / s',
    body: 'A cell takes in oxygen and nutrients and expels waste across its surface, but the demand for those exchanges comes from its whole volume. For a cube of side s the surface area is 6s² and the volume s³, so the ratio SA : V = 6/s — for a sphere it is 3/r — which means the ratio falls as the cell grows. Fick’s law says the rate of diffusion is proportional to surface area times concentration gradient divided by distance, so a large cell has too little surface for its volume and too far for molecules to travel to its center; most cells therefore stay between 10 and 100 µm. Living things get around the limit by dividing into many cells, by flattening or elongating, by folding membranes (microvilli in the gut, cristae in mitochondria), and, in large animals, by building dedicated exchange surfaces such as the roughly 70 m² of alveoli in a pair of human lungs.',
    example: 'A 1 µm cube has surface area 6 µm² and volume 1 µm³, so SA : V = 6 : 1. A 10 µm cube has surface area 600 µm² and volume 1,000 µm³, so SA : V = 0.6 : 1 — ten times less surface per unit of volume. At 100 µm the ratio drops to 0.06. Now split that 10 µm cube into 1,000 cubes of 1 µm: the total volume is still 1,000 µm³, but the total surface is 6,000 µm², ten times more. That is the whole reason an elephant is made of trillions of small cells rather than one enormous one.',
    pitfall: 'Bigger cells do have more surface area — the mistake is assuming that helps. When a length doubles, surface area grows by 2² = 4 times but volume by 2³ = 8 times, so surface per unit volume is cut in half. A related myth is that large animals have large cells: an elephant’s cells are about the same size as a mouse’s; the elephant simply has more of them.',
    href: '/tools/cell-size/',
    cta: 'Compare cell sizes',
    icon: '◫',
    keywords: 'surface area to volume ratio cell size diffusion why cells are small cube sphere',
    related: ['cell-transport', 'cell-theory'],
  },
  {
    slug: 'lab-measurements',
    title: 'Lab measurements & scale',
    subtitle: 'Turn what you see in a microscope into numbers.',
    formula: 'Magnification = image size ÷ actual size · C₁V₁ = C₂V₂',
    body: 'Magnification is image size divided by actual size (rearranged: image = actual × magnification), and it only works when both sizes are in the same unit — 1 mm = 1,000 µm and 1 µm = 1,000 nm. A light microscope’s total magnification is eyepiece × objective (10× × 40× = 400×), but its resolution is limited to about 200 nm, which is why ribosomes and membranes need an electron microscope. A scale bar is a line drawn on an image that represents a stated real length; its drawn length is that real length times the magnification, and unlike a printed "×400" it stays correct when the image is resized. For solutions, C₁V₁ = C₂V₂ says the amount of solute is conserved when you dilute, so you can find the volume of stock needed for any target concentration; whatever you calculate, round to the significant figures your instrument can actually justify.',
    example: 'A drawing of a cheek cell measures 30 mm across, and the real cell is 60 µm wide. Convert first: 30 mm = 30,000 µm, so magnification = 30,000 / 60 = 500×. To add a scale bar representing 20 µm, draw it 20 × 500 = 10,000 µm = 10 mm long. In the same lab, to make 50 mL of 0.2 M sucrose from a 1.0 M stock: V₁ = C₂V₂ / C₁ = 0.2 × 50 / 1.0 = 10 mL of stock, made up to 50 mL with 40 mL of water.',
    pitfall: 'Dividing 30 mm by 60 µm without converting gives 0.5 — a nonsense answer that would mean the drawing is smaller than the cell. Always convert both measurements to the same unit before dividing. And a calculator’s 500.00× does not mean you measured that precisely: a ruler reads to the nearest millimeter, so 500× (two significant figures) is the honest answer.',
    href: '/tools/magnification-calculator/',
    cta: 'Calculate magnification and scale bars',
    icon: '⌖',
    keywords: 'magnification formula scale bar mm to µm dilution c1v1 c2v2 significant figures',
    related: ['surface-area-to-volume', 'cell-theory'],
  },
];
