// Cell atlas data: eight organelles (fixed slug order) plus the two reference cell types drawn by CellDiagram.astro.
// Every number is a textbook value; keep `properties[0]` as the membrane row (the comparison table reads it).
export const organelles = {
  nucleus: {
    title: 'Nucleus',
    type: 'Organelle · double membrane',
    foundIn: ['Animal cells', 'Plant cells', 'Fungi', 'Protists'],
    intro: 'The nucleus stores the cell’s DNA and decides which genes are read at any moment. Its double membrane, the nuclear envelope, is pierced by pores that let RNA and proteins pass between nucleus and cytoplasm.',
    properties: [
      ['Membranes', 'Two: the nuclear envelope, whose outer membrane is continuous with the rough ER'],
      ['Typical size', 'About 5–10 µm across, usually the largest organelle in an animal cell'],
      ['Number per cell', 'One in most cells; skeletal muscle fibers carry hundreds, mature red blood cells have none'],
      ['Contains', 'Chromatin (DNA wound around histone proteins), one or more nucleoli, and nucleoplasm'],
      ['Discovered', 'Named by Robert Brown in 1831, who noticed it in orchid epidermal cells'],
    ],
    functions: [
      ['Stores the genome', 'A human nucleus holds 46 chromosomes, about 2 m of DNA folded into a space a few micrometers wide'],
      ['Runs transcription', 'RNA polymerase copies genes into messenger RNA here; the message is spliced and capped before it leaves'],
      ['Builds ribosome parts', 'The nucleolus assembles ribosomal subunits from rRNA and imported proteins'],
      ['Separates copying from reading', 'Keeping DNA behind a membrane lets the cell edit mRNA before ribosomes ever see it'],
    ],
    example: 'When blood glucose rises, a pancreatic β-cell ramps up transcription of the insulin gene inside its nucleus. The pre-mRNA is capped, spliced, and tailed there, then leaves through one of the roughly 2,000–5,000 nuclear pores, each about 120 nm wide, to be translated on the rough ER within minutes.',
    pitfall: 'The nucleus is often called the “brain” of the cell, but it does not think or issue commands. It is an archive and copy room: genes are switched on or off by signals arriving from the cytoplasm, and the proteins that actually do the work are built outside it.',
    related: ['ribosome', 'endoplasmic-reticulum'],
    lesson: 'dna-structure',
    keywords: 'nucleus function nuclear envelope nuclear pore chromatin nucleolus',
  },
  mitochondrion: {
    title: 'Mitochondrion',
    type: 'Organelle · double membrane',
    foundIn: ['Animal cells', 'Plant cells', 'Fungi', 'Protists'],
    intro: 'Mitochondria run aerobic respiration, converting the energy in glucose and fats into ATP the cell can spend. Their folded inner membrane and their own small genome are relics of free-living bacteria.',
    properties: [
      ['Membranes', 'Two: a smooth outer membrane and a deeply folded inner membrane (the folds are cristae)'],
      ['Typical size', 'About 0.5–1 µm wide and 1–10 µm long, roughly the size of a bacterium'],
      ['Number per cell', 'From a handful to thousands; a liver cell holds about 1,000–2,000'],
      ['Contains', 'A matrix with the Krebs-cycle enzymes, its own circular DNA (16,569 base pairs in humans), and bacterial-type ribosomes'],
      ['Discovered', 'Named by Carl Benda in 1898; the endosymbiotic origin was argued convincingly by Lynn Margulis in 1967'],
    ],
    functions: [
      ['Makes ATP by aerobic respiration', 'Oxidative phosphorylation across the cristae yields about 30–32 ATP per glucose (older textbooks quote up to 38)'],
      ['Runs the Krebs cycle', 'Pyruvate from glycolysis is oxidized to CO₂ in the matrix, loading NADH and FADH₂ for the electron transport chain'],
      ['Signals and stores', 'Buffers Ca²⁺ and releases cytochrome c to start apoptosis when a cell is beyond repair'],
      ['Produces heat', 'Brown-fat mitochondria let protons leak through UCP1, turning the gradient into warmth for newborns and hibernators'],
    ],
    example: 'A heart muscle cell is packed with mitochondria, which take up roughly a third of its volume, because it never rests. Each glucose molecule yields just 2 ATP from glycolysis in the cytoplasm but about 28 more inside the mitochondrion, so cutting off oxygen cuts the cell’s energy income by over 90% within minutes.',
    pitfall: '“The powerhouse of the cell” makes it sound as if mitochondria create energy. They do not: they convert chemical energy already stored in glucose and fatty acids into ATP and release the rest as heat. Energy is conserved, so without fuel and oxygen a mitochondrion produces nothing.',
    related: ['chloroplast', 'cell-membrane'],
    lesson: 'cellular-respiration',
    keywords: 'mitochondria function cristae matrix ATP aerobic respiration',
  },
  chloroplast: {
    title: 'Chloroplast',
    type: 'Plastid · double membrane',
    foundIn: ['Plant cells', 'Algae and some protists'],
    intro: 'Chloroplasts capture light energy and use it to build sugar from carbon dioxide and water. Stacked membrane discs called thylakoids hold the chlorophyll; the fluid stroma around them runs the Calvin cycle.',
    properties: [
      ['Membranes', 'Two envelope membranes plus a third internal system, the thylakoids, arranged in stacks called grana'],
      ['Typical size', 'Lens-shaped, about 3–10 µm long and 1–3 µm thick'],
      ['Number per cell', 'Around 30–100 in a leaf mesophyll cell; the alga Chlamydomonas has a single cup-shaped chloroplast'],
      ['Contains', 'Chlorophyll a and b, carotenoids, grana, stroma, starch grains, circular DNA, and 70S ribosomes'],
      ['Discovered', 'Chlorophyll was named in 1817 by Pelletier and Caventou; Andreas Schimper described chloroplasts in 1883'],
    ],
    functions: [
      ['Runs the light reactions', 'Chlorophyll in the thylakoid membranes splits water, releasing O₂ and charging up ATP and NADPH'],
      ['Fixes carbon in the Calvin cycle', 'In the stroma, RuBisCO attaches CO₂ to a 5-carbon sugar and the cycle turns it into 3-carbon sugars'],
      ['Stores starch', 'Surplus sugar is banked as starch grains by day and mobilized at night'],
    ],
    example: 'A spinach leaf cell holding about 50 chloroplasts runs the summary equation 6 CO₂ + 6 H₂O + light → C₆H₁₂O₆ + 6 O₂. Because the light reactions need at least 8 photons per O₂ released, one glucose costs a minimum of 48 photons. RuBisCO, the enzyme that grabs CO₂, is so slow (about 3 reactions per second per active site) that leaves compensate by making it up to half of their soluble protein.',
    pitfall: 'Plants do not “breathe in CO₂ and out O₂ instead of respiring.” Every plant cell has mitochondria and respires day and night; in the light, photosynthesis in the chloroplasts simply outpaces respiration, so the net gas exchange flips.',
    related: ['mitochondrion', 'ribosome'],
    lesson: 'photosynthesis',
    keywords: 'chloroplast function thylakoid grana stroma chlorophyll photosynthesis',
  },
  ribosome: {
    title: 'Ribosome',
    type: 'Molecular machine · no membrane',
    foundIn: ['Animal cells', 'Plant cells', 'Fungi', 'Protists', 'Bacteria and archaea'],
    intro: 'Ribosomes read messenger RNA three bases at a time and link amino acids into proteins. They have no membrane and occur in every living cell, from bacteria to humans.',
    properties: [
      ['Membranes', 'None: built from ribosomal RNA and dozens of proteins'],
      ['Typical size', 'About 20–30 nm across, far too small to see with a light microscope'],
      ['Number per cell', 'Roughly 20,000 in a growing E. coli cell; several million in a mammalian cell'],
      ['Structure', 'Two subunits: 80S (60S + 40S) in eukaryotes, 70S (50S + 30S) in prokaryotes, with three tRNA sites (A, P, E)'],
      ['Discovered', 'Spotted by George Palade in 1955 with the electron microscope; the name “ribosome” dates from 1958'],
    ],
    functions: [
      ['Translates mRNA into protein', 'Matches each codon with a tRNA and forms a peptide bond, at about 15–20 amino acids per second in bacteria and 5–6 in eukaryotes'],
      ['Sorts proteins by where it sits', 'Free ribosomes make proteins for the cytosol; ribosomes docked on the rough ER make secreted and membrane proteins'],
      ['Checks the message', 'Stalls on damaged or truncated mRNA so rescue factors can recycle the ribosome and destroy the faulty message'],
    ],
    example: 'The β-chain of hemoglobin is 146 amino acids long. A eukaryotic ribosome adding about 5 amino acids per second finishes one chain in roughly 30 seconds, and because a single mRNA is usually read by several ribosomes at once (a polysome), a developing red blood cell turns out hemoglobin fast enough to fill itself with about 270 million molecules.',
    pitfall: 'Ribosomes do not make amino acids, and they are not membrane-bound organelles. Amino acids come from food or the cell’s own metabolism; the ribosome only stitches them together in the order the mRNA dictates. Antibiotics such as tetracycline exploit the 70S/80S difference to hit bacterial ribosomes and spare ours.',
    related: ['endoplasmic-reticulum', 'nucleus'],
    lesson: 'transcription-and-translation',
    keywords: 'ribosome function 80S 70S translation rough ER free ribosome',
  },
  'endoplasmic-reticulum': {
    title: 'Endoplasmic reticulum',
    type: 'Organelle · single membrane network',
    foundIn: ['Animal cells', 'Plant cells', 'Fungi', 'Protists'],
    intro: 'The endoplasmic reticulum (ER) is a maze of membrane tubes and sacs continuous with the nuclear envelope. Rough ER, studded with ribosomes, folds and packages proteins; smooth ER makes lipids and detoxifies drugs.',
    properties: [
      ['Membranes', 'One continuous membrane enclosing a single internal space, the lumen'],
      ['Typical size', 'Tubules about 30–100 nm wide; the network can account for more than half of all membrane in a cell'],
      ['Number per cell', 'One interconnected network whose balance shifts: liver cells are rich in smooth ER, antibody-secreting cells in rough ER'],
      ['Structure', 'Rough ER: flattened cisternae dotted with ribosomes. Smooth ER: branching tubules without ribosomes'],
      ['Discovered', 'Seen by Keith Porter, Albert Claude, and Ernest Fullam in 1945 with one of the first electron microscopes'],
    ],
    functions: [
      ['Folds and modifies proteins', 'Rough ER threads new polypeptides into its lumen, attaches sugar chains (N-linked glycosylation), and folds them with chaperones'],
      ['Builds lipids', 'Smooth ER makes phospholipids and cholesterol and, in gonads and adrenal glands, steroid hormones'],
      ['Detoxifies', 'Liver smooth ER carries cytochrome P450 enzymes that oxidize drugs, alcohol, and other toxins'],
      ['Stores calcium', 'In muscle, the sarcoplasmic reticulum holds Ca²⁺ and releases it to trigger contraction'],
    ],
    example: 'A plasma cell devoted to antibody production is crammed with rough ER and releases about 2,000 antibody molecules per second; each one is folded and glycosylated in the ER lumen before shipment. In the liver, a few days of barbiturate exposure makes hepatocytes roughly double their smooth ER, which is one reason the drug loses its effect over time.',
    pitfall: 'Rough and smooth ER are not two separate organelles. They are regions of one continuous membrane system, and ribosomes attach and detach as the cell’s needs change, so a cell can shift the balance between them within hours.',
    related: ['ribosome', 'golgi-apparatus'],
    lesson: 'transcription-and-translation',
    keywords: 'endoplasmic reticulum function rough ER smooth ER cisternae lumen',
  },
  'golgi-apparatus': {
    title: 'Golgi apparatus',
    type: 'Organelle · single membrane stacks',
    foundIn: ['Animal cells', 'Plant cells', 'Fungi', 'Protists'],
    intro: 'The Golgi apparatus receives proteins and lipids from the ER, finishes them, and sorts them into vesicles for delivery. Cargo goes to the cell membrane, to lysosomes, or out of the cell: think of a mail room that modifies, labels, addresses, and ships.',
    properties: [
      ['Membranes', 'One membrane per cisterna; a stack usually holds 4–8 flattened cisternae'],
      ['Typical size', 'Each cisterna is about 1 µm across; a stack is roughly 0.5–2 µm thick'],
      ['Number per cell', 'One ribbon of linked stacks near the nucleus in animal cells; dozens to hundreds of separate stacks (dictyosomes) in plant cells'],
      ['Structure', 'A cis face receives vesicles from the ER, medial cisternae modify the cargo, and the trans face buds off vesicles for delivery'],
      ['Discovered', 'Stained and described by Camillo Golgi in 1898; dismissed as an artifact by many until electron microscopy confirmed it in the 1950s'],
    ],
    functions: [
      ['Modifies proteins and lipids', 'Trims and rebuilds sugar chains, and adds sulfate or phosphate groups as cargo moves from cis to trans'],
      ['Sorts and ships', 'Tags lysosomal enzymes with mannose-6-phosphate and packs secreted proteins into vesicles headed for the cell membrane'],
      ['Builds plant cell-wall polysaccharides', 'Makes the pectins and hemicelluloses of the wall (cellulose itself is made at the cell membrane)'],
      ['Seeds lysosomes', 'Vesicles that bud from the trans face mature into lysosomes'],
    ],
    example: 'The mucins that coat your gut are up to 80% sugar by mass, and nearly all of that carbohydrate is attached in the Golgi. A goblet cell in the intestinal lining refills and releases its mucin granules within hours, while a typical protein takes on the order of 20 minutes to cross a Golgi stack from the cis face to the trans face.',
    pitfall: 'The Golgi is not just a “packaging center” that wraps things in membrane. It edits what it receives, and its address tags decide where each protein ends up. In I-cell disease the mannose-6-phosphate tag is missing, so lysosomal enzymes are shipped out of the cell instead of into lysosomes.',
    related: ['endoplasmic-reticulum', 'lysosome'],
    lesson: 'cell-transport',
    keywords: 'golgi apparatus function cisternae cis trans vesicles secretion',
  },
  lysosome: {
    title: 'Lysosome',
    type: 'Organelle · single membrane',
    foundIn: ['Animal cells', 'Protists', 'Fungi and plants (as lytic vacuoles)'],
    intro: 'Lysosomes are acidic sacs of enzymes that digest worn-out organelles, engulfed microbes, and large molecules. The pieces are recycled as building blocks, and a single membrane keeps roughly 50 kinds of hydrolase safely walled off from the cytosol.',
    properties: [
      ['Membranes', 'One, with a heavily glycosylated inner face that resists the enzymes inside'],
      ['Typical size', 'About 0.1–1.2 µm across, so it varies from a tiny vesicle to a mitochondrion-sized sac'],
      ['Number per cell', 'Tens to a few hundred in a typical animal cell; far more in macrophages'],
      ['Contains', 'Around 50 acid hydrolases (proteases, lipases, nucleases, glycosidases) that work best at pH 4.5–5.0'],
      ['Discovered', 'Identified biochemically by Christian de Duve in 1955, work that earned the 1974 Nobel Prize'],
    ],
    functions: [
      ['Digests what the cell takes in', 'Breaks down proteins, lipids, carbohydrates, and nucleic acids delivered by endocytosis and phagocytosis'],
      ['Recycles the cell’s own parts', 'Autophagy delivers old mitochondria and other organelles for breakdown, returning amino acids and lipids to the cytosol'],
      ['Defends', 'In white blood cells, destroys engulfed bacteria; in osteoclasts, its enzymes are released to dissolve bone'],
      ['Senses nutrients', 'The lysosome surface is where the mTORC1 complex decides whether the cell grows or recycles'],
    ],
    example: 'A proton pump (V-type ATPase) holds the lysosome interior at pH 4.5–5.0 while the cytosol sits near pH 7.2, a 100- to 500-fold difference in H⁺ concentration. That acidity is a safety feature too: if a lysosome leaks, its enzymes are nearly inactive at cytosolic pH. In Tay–Sachs disease one missing hydrolase (hexosaminidase A) lets GM2 ganglioside pile up in neurons, showing how much a single enzyme matters.',
    pitfall: 'Lysosomes are not “suicide sacs” waiting to burst and kill the cell. Programmed cell death is run by caspase enzymes, not lysosomal ones, and a leaked hydrolase does little at neutral pH. Lysosomes are recyclers first, and they are also unusually rare in plant cells, where the central vacuole does the digesting.',
    related: ['golgi-apparatus', 'cell-membrane'],
    lesson: 'enzymes',
    keywords: 'lysosome function acid hydrolase pH autophagy phagocytosis',
  },
  'cell-membrane': {
    title: 'Cell membrane',
    type: 'Boundary · phospholipid bilayer',
    foundIn: ['Animal cells', 'Plant cells', 'Fungi', 'Protists', 'Bacteria and archaea'],
    intro: 'The cell membrane, or plasma membrane, is a phospholipid bilayer about 7–8 nm thick that separates a cell from its surroundings. Embedded proteins let it choose what enters and leaves, receive signals, and hold on to neighbors.',
    properties: [
      ['Membranes', 'It is one: a bilayer with hydrophilic phosphate heads facing out and hydrophobic fatty-acid tails facing in'],
      ['Thickness', 'About 7–8 nm, invisible under a light microscope'],
      ['Number per cell', 'One continuous sheet; a human red blood cell has about 140 µm² of it'],
      ['Composition', 'Roughly half lipid and half protein by mass in a typical animal cell, with about 50 lipid molecules for every protein, plus cholesterol and a sugar-coat (glycocalyx)'],
      ['Model', 'The fluid mosaic model, proposed by S. J. Singer and Garth Nicolson in 1972'],
    ],
    functions: [
      ['Controls what gets in and out', 'Small nonpolar molecules such as O₂ and CO₂ diffuse straight through; ions and sugars need channel or carrier proteins'],
      ['Pumps against the gradient', 'The Na⁺/K⁺-ATPase moves 3 Na⁺ out and 2 K⁺ in per ATP, setting the cell’s charge and volume'],
      ['Receives signals', 'Receptor proteins bind hormones such as insulin and relay the message inside'],
      ['Identifies and connects', 'Glycoproteins act as ID tags (the ABO blood groups are membrane sugars) and junction proteins knit cells into tissues'],
    ],
    example: 'Drop a red blood cell into pure water and it swells and bursts within seconds: water crosses the membrane freely but the salts inside cannot follow. Keeping the balance is expensive, since the Na⁺/K⁺ pump alone burns roughly a third of a typical animal cell’s ATP, and far more in neurons, to hold a resting potential of about −70 mV.',
    pitfall: 'The membrane is neither a rigid wall nor a simple sieve that sorts by size. Its lipids drift sideways constantly (one can travel the length of a bacterium in about a second), and a tiny ion like Na⁺ is blocked while much larger nonpolar steroid hormones slip straight through: polarity matters more than size.',
    related: ['lysosome', 'golgi-apparatus'],
    lesson: 'cell-transport',
    keywords: 'cell membrane function phospholipid bilayer fluid mosaic selective permeability',
  },
};

// Reference cells drawn by CellDiagram.astro. `organelles` lists the atlas slugs present; `extras` are labeled structures without an atlas page: [name, description, short key note].
export const cellTypes = {
  animal: {
    title: 'Animal cell',
    description: 'A flexible, roughly rounded cell 10–30 µm across, bounded only by its membrane. It has a pair of centrioles near the nucleus and many lysosomes, but no wall, no chloroplasts, and no large central vacuole.',
    organelles: ['nucleus', 'mitochondrion', 'ribosome', 'endoplasmic-reticulum', 'golgi-apparatus', 'lysosome', 'cell-membrane'],
    extras: [
      ['Centrioles', 'A pair of short microtubule cylinders at right angles; they organize the spindle during cell division.', 'Microtubule pair · organizes the spindle'],
    ],
  },
  plant: {
    title: 'Plant cell',
    description: 'A boxy cell 10–100 µm across held rigid by a cellulose wall outside the membrane. A large central vacuole fills most of the interior, chloroplasts line the cytoplasm, and there are no centrioles or true lysosomes.',
    organelles: ['nucleus', 'mitochondrion', 'chloroplast', 'ribosome', 'endoplasmic-reticulum', 'golgi-apparatus', 'cell-membrane'],
    extras: [
      ['Cell wall', 'A rigid layer of cellulose fibers outside the membrane, typically 0.1–10 µm thick, that gives the cell its shape and resists turgor pressure.', 'Cellulose layer · outside the membrane'],
      ['Central vacuole', 'A water-filled sac bounded by the tonoplast that can occupy 80–90% of the cell’s volume; it stores water, ions, and pigments and keeps the cell turgid.', 'Water-filled sac · up to 90% of the volume'],
    ],
  },
};
