// Practice question bank: 100 multiple-choice biology questions, 20 per topic.
// Hand-written conceptual questions come first; numeric questions are generated below with distinct distractors.
// Shape: {topic, q, choices:[4 unique strings], answer:index of the correct choice, why:1–2 teaching sentences}.
export const TOPICS=['cells','genetics','molecular','ecology','physiology'];
export const QUESTIONS=[
 // ---- Cells: structure, organelles, membranes, transport, mitosis and meiosis ----
 {topic:'cells',q:'Which organelle is the main site of aerobic respiration and ATP production?',choices:['Mitochondrion','Chloroplast','Ribosome','Golgi apparatus'],answer:0,why:'Mitochondria house the Krebs cycle and the electron transport chain, which together make most of a cell’s ATP. Chloroplasts capture light energy rather than releasing energy from glucose.'},
 {topic:'cells',q:'Which structure is found in plant cells but never in animal cells?',choices:['Cellulose cell wall','Mitochondrion','Cell membrane','Ribosome'],answer:0,why:'Plant cells are wrapped in a rigid cellulose wall outside the membrane; animal cells have only a membrane. Mitochondria, membranes, and ribosomes are found in both.'},
 {topic:'cells',q:'Which organelle modifies, sorts, and packages proteins for secretion?',choices:['Golgi apparatus','Smooth endoplasmic reticulum','Nucleus','Mitochondrion'],answer:0,why:'Proteins made on the rough ER travel in vesicles to the Golgi apparatus, which adds sugar tags, sorts them, and ships them in vesicles to the membrane or to lysosomes.'},
 {topic:'cells',q:'What is the main job of a lysosome?',choices:['Digesting worn-out organelles and waste with hydrolytic enzymes','Producing ATP by respiration','Storing water and ions in plant cells','Building the spindle during mitosis'],answer:0,why:'Lysosomes are acidic sacs of hydrolytic enzymes that break down old organelles, engulfed bacteria, and macromolecules so the parts can be recycled.'},
 {topic:'cells',q:'Which of these organisms is a prokaryote?',choices:['Escherichia coli','Baker’s yeast','Amoeba','A human'],answer:0,why:'Prokaryotes such as the bacterium E. coli have no nucleus or membrane-bound organelles. Yeast, amoebae, and humans are eukaryotes, built from cells with a true nucleus.'},
 {topic:'cells',q:'The net movement of water across a partially permeable membrane from high to low water potential is called what?',choices:['Osmosis','Active transport','Endocytosis','Simple diffusion of solutes'],answer:0,why:'Osmosis is the passive diffusion of water itself across a partially permeable membrane, always down the water potential gradient. No ATP is needed.'},
 {topic:'cells',q:'Which feature is true of active transport but not of diffusion?',choices:['It moves substances against their concentration gradient using ATP','It only moves gases','It requires no membrane proteins','It only happens in plant cells'],answer:0,why:'Active transport uses carrier proteins powered by ATP to pump molecules from low to high concentration, as the sodium–potassium pump does. Diffusion runs the other way and needs no energy input.'},
 {topic:'cells',q:'The current model of the cell membrane is known as the what?',choices:['Fluid mosaic model','Lock-and-key model','Induced-fit model','Semi-conservative model'],answer:0,why:'In the fluid mosaic model a phospholipid bilayer flows like a two-dimensional liquid while proteins and cholesterol float within it like tiles in a mosaic.'},
 {topic:'cells',q:'During which stage of mitosis do the chromosomes line up along the equator of the cell?',choices:['Metaphase','Prophase','Anaphase','Telophase'],answer:0,why:'In metaphase the spindle fibers pull the chromosomes into a line at the metaphase plate. Sister chromatids are separated in the next stage, anaphase.'},
 {topic:'cells',q:'Meiosis in a diploid cell produces how many cells, and with what chromosome number?',choices:['Four haploid cells','Two diploid cells','Four diploid cells','Two haploid cells'],answer:0,why:'Two rounds of division follow one round of DNA replication, so meiosis yields four genetically different haploid cells. Mitosis yields two identical diploid cells.'},
 {topic:'cells',q:'A human body cell contains 46 chromosomes. How many chromosomes does a human sperm or egg contain?',choices:['23','46','92','12'],answer:0,why:'Gametes are haploid: meiosis halves the chromosome number from 46 to 23 so that fertilization restores the diploid number of 46.'},
 // ---- Genetics: inheritance, blood types, sex linkage, Hardy-Weinberg, evolution ----
 {topic:'genetics',q:'An organism carrying two different alleles of a gene, such as Bb, is described as what?',choices:['Heterozygous','Homozygous dominant','Homozygous recessive','Hemizygous'],answer:0,why:'Hetero- means different: a heterozygote carries two different alleles of a gene, for example one dominant and one recessive (Bb). Homozygotes carry two copies of the same allele, BB or bb.'},
 {topic:'genetics',q:'Which cross is used to find out whether an organism showing a dominant trait is homozygous or heterozygous?',choices:['A test cross with a homozygous recessive partner','A cross with a homozygous dominant partner','Self-fertilization of a recessive plant','A dihybrid cross between two heterozygotes'],answer:0,why:'Crossing the unknown with a homozygous recessive (aa) reveals its genotype: if any offspring show the recessive trait, the unknown parent must be heterozygous.'},
 {topic:'genetics',q:'Mendel’s law of segregation states that the two alleles for a gene separate during which process?',choices:['Meiosis, when gametes form','Mitosis, when body cells divide','Fertilization','Transcription'],answer:0,why:'Homologous chromosomes, and therefore the two alleles they carry, are pulled apart in meiosis I, so each gamete receives just one allele for each gene.'},
 {topic:'genetics',q:'A parent with blood type AB and a parent with blood type O can have children of which blood types?',choices:['Type A or type B only','Type AB or type O only','Type O only','Any of A, B, AB, or O'],answer:0,why:'The AB parent gives either the Iᴬ or the Iᴮ allele and the O parent always gives i, so each child is Iᴬi (type A) or Iᴮi (type B). Neither AB nor O is possible.'},
 {topic:'genetics',q:'Red-green color blindness is X-linked recessive. A color-blind father and a homozygous normal mother have a son. What is the chance he is color-blind?',choices:['0%','50%','100%','25%'],answer:0,why:'A son inherits his X chromosome from his mother and his Y from his father. Because the mother carries two normal alleles, no son can be color-blind, though every daughter will be a carrier.'},
 {topic:'genetics',q:'In snapdragons, red × white flowers give all pink offspring. What ratio results from crossing two pink plants?',choices:['1 red : 2 pink : 1 white','3 pink : 1 white','All pink','1 red : 1 white'],answer:0,why:'Pink flowers show incomplete dominance: heterozygotes have an intermediate color. Crossing two heterozygotes gives 1 RR (red) : 2 RW (pink) : 1 WW (white).'},
 {topic:'genetics',q:'Human AB blood type, in which both the A and B antigens appear on red cells, is an example of what?',choices:['Codominance','Incomplete dominance','Complete dominance','Polygenic inheritance'],answer:0,why:'In codominance both alleles are fully expressed at once, so an IᴬIᴮ person makes both antigens. Incomplete dominance would blend them into an intermediate phenotype.'},
 {topic:'genetics',q:'Which condition is NOT required for a population to stay in Hardy-Weinberg equilibrium?',choices:['Natural selection favoring one allele','Random mating','A very large population','No migration in or out'],answer:0,why:'Equilibrium assumes no selection, no mutation, no migration, random mating, and a large population. Selection changes allele frequencies, so it breaks the equilibrium.'},
 {topic:'genetics',q:'What is the ultimate source of new alleles in a population?',choices:['Mutation','Natural selection','Genetic drift','Migration'],answer:0,why:'Only mutation creates new versions of a gene. Selection, drift, and migration change how common existing alleles are but cannot invent new ones.'},
 {topic:'genetics',q:'Genetic drift, the random change in allele frequencies between generations, has the largest effect in which kind of population?',choices:['A very small population','A very large population','A population with no mutations','A population with random mating'],answer:0,why:'Chance events such as which individuals happen to reproduce matter most when there are few individuals, as in bottleneck and founder effects. Large populations average out the randomness.'},
 {topic:'genetics',q:'The forelimbs of whales, bats, and humans share the same bone pattern despite different uses. Such structures are evidence of what?',choices:['Common ancestry (homologous structures)','Convergent evolution (analogous structures)','Vestigial organs','Artificial selection'],answer:0,why:'Homologous structures share a bone layout because they were inherited from a common ancestor and then modified. Analogous structures, such as bird and insect wings, evolved similar functions independently.'},
 {topic:'genetics',q:'Which statement best describes how natural selection works?',choices:['Individuals with heritable traits suited to the environment leave more offspring, so those traits become more common','Organisms change their traits during life to fit the environment and pass those changes on','Populations evolve because they need to','Every mutation is beneficial and spreads through the population'],answer:0,why:'Selection acts on existing heritable variation: better-adapted individuals survive and reproduce more, shifting allele frequencies over generations. Lamarck’s idea of inheriting acquired traits is not how it works.'},
 // ---- Molecular: DNA, RNA, protein synthesis, enzymes, photosynthesis, respiration ----
 {topic:'molecular',q:'In a DNA double helix, adenine always pairs with which base?',choices:['Thymine','Guanine','Cytosine','Uracil'],answer:0,why:'Complementary base pairing joins A to T with two hydrogen bonds and G to C with three. Uracil replaces thymine only in RNA.'},
 {topic:'molecular',q:'Which sugar is found in the backbone of RNA?',choices:['Ribose','Deoxyribose','Glucose','Sucrose'],answer:0,why:'RNA nucleotides contain ribose, which has a hydroxyl group on its 2′ carbon. DNA uses deoxyribose, which lacks that oxygen and is more chemically stable.'},
 {topic:'molecular',q:'In a eukaryotic cell, where does transcription of a nuclear gene into mRNA take place?',choices:['In the nucleus','On a ribosome in the cytoplasm','In the mitochondrial matrix','In the Golgi apparatus'],answer:0,why:'RNA polymerase copies the gene inside the nucleus, where the DNA is kept. The processed mRNA then leaves through nuclear pores to be translated on ribosomes.'},
 {topic:'molecular',q:'Which enzyme adds nucleotides to a growing DNA strand during replication?',choices:['DNA polymerase','DNA helicase','RNA polymerase','DNA ligase'],answer:0,why:'DNA polymerase matches free nucleotides to the template strand and joins them in the 5′→3′ direction. Helicase unzips the helix and ligase seals gaps between fragments.'},
 {topic:'molecular',q:'Which molecule carries a specific amino acid to the ribosome and matches it to a codon on the mRNA?',choices:['Transfer RNA (tRNA)','Messenger RNA (mRNA)','Ribosomal RNA (rRNA)','DNA polymerase'],answer:0,why:'Each tRNA carries an anticodon that base-pairs with an mRNA codon while delivering the matching amino acid, so the sequence of codons becomes a sequence of amino acids.'},
 {topic:'molecular',q:'The start codon AUG signals the beginning of translation and codes for which amino acid?',choices:['Methionine','Glycine','No amino acid (it is a stop signal)','Tryptophan'],answer:0,why:'AUG both starts translation and codes for methionine, so almost every newly made polypeptide begins with Met. UAA, UAG, and UGA are the three stop codons.'},
 {topic:'molecular',q:'A point mutation changes a codon from GAA to GAG, and both code for glutamic acid. What kind of mutation is this?',choices:['Silent mutation','Missense mutation','Nonsense mutation','Frameshift mutation'],answer:0,why:'Because the genetic code is degenerate, several codons can specify the same amino acid. A base change that leaves the protein unchanged is silent.'},
 {topic:'molecular',q:'How does an enzyme speed up a chemical reaction?',choices:['By lowering the activation energy','By raising the temperature of the cell','By being used up to supply energy','By shifting the equilibrium position of the reaction'],answer:0,why:'Enzymes bind substrates at the active site and stabilize the transition state, lowering the activation energy barrier. They are not consumed and do not change the final equilibrium.'},
 {topic:'molecular',q:'What happens to most human enzymes when they are heated well above 40 °C?',choices:['They denature as the active site loses its shape','They work faster and faster without limit','They are converted into substrate','They become permanently more stable'],answer:0,why:'Heat breaks the weak bonds that hold the tertiary structure, so the active site changes shape and no longer fits the substrate. Rate rises with temperature only until this denaturation begins.'},
 {topic:'molecular',q:'The oxygen gas released during photosynthesis comes from which molecule?',choices:['Water (H₂O)','Carbon dioxide (CO₂)','Glucose','ATP'],answer:0,why:'In the light-dependent reactions water is split (photolysis) to supply electrons and protons, and its oxygen is released as O₂. The carbon in CO₂ ends up in sugar.'},
 {topic:'molecular',q:'Which stage of aerobic respiration produces the most ATP?',choices:['Oxidative phosphorylation at the electron transport chain','Glycolysis','The Krebs (citric acid) cycle','The link reaction (pyruvate oxidation)'],answer:0,why:'Glycolysis and the Krebs cycle make only 4 ATP directly per glucose. The electron transport chain and ATP synthase in the inner mitochondrial membrane generate roughly 26–28 more.'},
 {topic:'molecular',q:'Where in the chloroplast does the Calvin cycle take place?',choices:['The stroma','The thylakoid membrane','The inner mitochondrial membrane','The cytoplasm'],answer:0,why:'The Calvin cycle uses ATP and NADPH from the light reactions to fix CO₂ into sugar in the stroma, the fluid surrounding the thylakoids where the light reactions occur.'},
 // ---- Ecology: food webs, energy, cycles, biomes, interactions, populations ----
 {topic:'ecology',q:'Organisms such as plants and algae that make their own food from light energy are called what?',choices:['Producers (autotrophs)','Primary consumers','Decomposers','Detritivores'],answer:0,why:'Producers fix carbon dioxide into sugars by photosynthesis, forming the first trophic level that every food chain rests on. Consumers must eat other organisms.'},
 {topic:'ecology',q:'Which trophic level normally contains the greatest total energy in an ecosystem?',choices:['Producers','Primary consumers','Secondary consumers','Top predators'],answer:0,why:'Only about 10% of the energy at one level is passed to the next, so energy is greatest at the base, where producers capture it, and falls with each step up the pyramid.'},
 {topic:'ecology',q:'Which organisms convert atmospheric nitrogen gas (N₂) into ammonia that plants can eventually use?',choices:['Nitrogen-fixing bacteria','Decomposing fungi','Herbivorous insects','Green algae'],answer:0,why:'Nitrogen-fixing bacteria, some free-living and some in root nodules of legumes, use the enzyme nitrogenase to reduce N₂ to ammonia. Plants cannot use N₂ directly.'},
 {topic:'ecology',q:'Which process returns carbon dioxide from living organisms to the atmosphere?',choices:['Cellular respiration','Photosynthesis','Nitrogen fixation','Transpiration'],answer:0,why:'Respiration by plants, animals, and decomposers releases CO₂ as glucose is broken down. Photosynthesis does the opposite, pulling CO₂ out of the air.'},
 {topic:'ecology',q:'Which biome is characterized by permanently frozen subsoil called permafrost?',choices:['Tundra','Tropical rainforest','Temperate grassland','Desert'],answer:0,why:'Arctic tundra has permafrost, short summers, and low-growing plants such as mosses and lichens. Trees cannot root in the frozen ground.'},
 {topic:'ecology',q:'Which biome holds the greatest biodiversity on land?',choices:['Tropical rainforest','Taiga (boreal forest)','Tundra','Savanna'],answer:0,why:'Warm temperatures, year-round sunlight, and heavy rainfall let tropical rainforests support more species per hectare than any other terrestrial biome.'},
 {topic:'ecology',q:'A relationship in which both species benefit, such as bees pollinating flowers while collecting nectar, is called what?',choices:['Mutualism','Parasitism','Commensalism','Predation'],answer:0,why:'In mutualism both partners gain. Commensalism helps one and leaves the other unaffected, while parasitism benefits one at the other’s expense.'},
 {topic:'ecology',q:'Sea otters eat sea urchins, which would otherwise destroy kelp forests. The otter is best described as what?',choices:['A keystone species','A pioneer species','An invasive species','A decomposer'],answer:0,why:'A keystone species has an effect on its community far larger than its abundance suggests. Remove the otters and urchins strip the kelp, collapsing the whole habitat.'},
 {topic:'ecology',q:'The maximum population size an environment can support over time is called its what?',choices:['Carrying capacity','Biotic potential','Ecological niche','Limiting factor'],answer:0,why:'Carrying capacity (K) is where births and deaths balance because food, space, or other resources have become limiting, so logistic growth levels off there.'},
 {topic:'ecology',q:'Which of these is a density-dependent limiting factor?',choices:['Spread of an infectious disease','A volcanic eruption','A severe drought','A late spring frost'],answer:0,why:'Disease, competition, and predation hit harder as populations become more crowded. Eruptions, droughts, and frosts affect populations regardless of their density.'},
 {topic:'ecology',q:'Which organisms would you expect to colonize bare rock first during primary succession?',choices:['Lichens and mosses','Oak trees','Grasses and shrubs','Deer and rabbits'],answer:0,why:'Lichens can grow on bare rock, slowly weathering it and adding organic matter to form the first thin soil. Grasses, shrubs, and finally trees follow as the soil deepens.'},
 {topic:'ecology',q:'What role do fungi and bacteria play in an ecosystem when they break down dead organisms?',choices:['Decomposers that recycle nutrients back into the soil','Producers that build sugars from light','Primary consumers that eat plants','Top predators at the end of food chains'],answer:0,why:'Decomposers digest dead matter and waste, releasing minerals such as nitrates and phosphates that producers take up again. Without them nutrients would stay locked in dead tissue.'},
 // ---- Physiology: circulation, respiration, digestion, nervous system, homeostasis, immunity ----
 {topic:'physiology',q:'Which type of blood vessel carries blood away from the heart?',choices:['Arteries','Veins','Capillaries','Venules'],answer:0,why:'Arteries carry blood away from the heart under high pressure, which is why they have thick, elastic walls. Veins return blood to the heart with the help of valves.'},
 {topic:'physiology',q:'Which chamber of the heart pumps oxygenated blood out to the body?',choices:['Left ventricle','Right ventricle','Left atrium','Right atrium'],answer:0,why:'Oxygenated blood returns from the lungs to the left atrium, then the thick-walled left ventricle pumps it into the aorta. The right ventricle pumps only to the lungs.'},
 {topic:'physiology',q:'Where in the lungs does gas exchange between air and blood take place?',choices:['In the alveoli','In the trachea','In the bronchi','In the diaphragm'],answer:0,why:'Millions of thin-walled alveoli wrapped in capillaries give a huge surface area for oxygen to diffuse into the blood and carbon dioxide to diffuse out.'},
 {topic:'physiology',q:'Which enzyme in saliva begins the digestion of starch in the mouth?',choices:['Amylase','Pepsin','Lipase','Trypsin'],answer:0,why:'Salivary amylase starts breaking starch into maltose. Pepsin digests protein in the stomach and lipase digests fats mainly in the small intestine.'},
 {topic:'physiology',q:'Most digested nutrients are absorbed into the blood from which organ?',choices:['The small intestine','The stomach','The large intestine','The esophagus'],answer:0,why:'The small intestine’s villi and microvilli create an enormous surface area for absorbing sugars, amino acids, and fatty acids. The large intestine mainly reabsorbs water.'},
 {topic:'physiology',q:'The pancreatic hormone insulin lowers blood glucose mainly by doing what?',choices:['Stimulating cells to take up glucose and the liver to store it as glycogen','Breaking glycogen down into glucose','Making the kidneys excrete glucose','Slowing the heart rate'],answer:0,why:'Insulin signals muscle, fat, and liver cells to absorb glucose from the blood and convert it to glycogen. Glucagon does the reverse when blood sugar falls.'},
 {topic:'physiology',q:'What is the name of the gap where a signal passes from one neuron to the next?',choices:['Synapse','Axon','Myelin sheath','Dendrite'],answer:0,why:'At a synapse the electrical impulse triggers release of neurotransmitter molecules that diffuse across the cleft and bind to receptors on the next neuron.'},
 {topic:'physiology',q:'What is the function of the myelin sheath around an axon?',choices:['It insulates the axon so impulses jump between nodes and travel faster','It produces neurotransmitters','It carries impulses toward the cell body','It supplies the neuron with glucose'],answer:0,why:'Myelin is a fatty insulating layer; the impulse jumps between the gaps (nodes of Ranvier) in saltatory conduction, which is much faster than steady conduction along a bare axon.'},
 {topic:'physiology',q:'Which cells of the immune system produce antibodies?',choices:['B lymphocytes (plasma cells)','Red blood cells','Platelets','Cytotoxic T cells'],answer:0,why:'Activated B cells become plasma cells that secrete antibodies matching a specific antigen. Cytotoxic T cells kill infected cells directly instead.'},
 {topic:'physiology',q:'How does a vaccine protect against a future infection?',choices:['It triggers the production of memory cells that respond quickly to the real pathogen','It kills all bacteria in the body','It permanently raises body temperature','It supplies ready-made antibodies for life'],answer:0,why:'A vaccine presents a harmless form of an antigen so the immune system makes memory B and T cells. On real exposure the secondary response is faster and stronger, often preventing illness.'},
 {topic:'physiology',q:'Sweating when hot and shivering when cold are examples of which kind of control mechanism?',choices:['Negative feedback (homeostasis)','Positive feedback','Reflex learning','Natural selection'],answer:0,why:'Negative feedback detects a change and triggers a response that reverses it, holding body temperature near 37 °C. Positive feedback, as in childbirth contractions, amplifies a change instead.'},
 {topic:'physiology',q:'Which part of the brain coordinates balance, posture, and fine muscle movement?',choices:['Cerebellum','Medulla oblongata','Cerebrum','Hypothalamus'],answer:0,why:'The cerebellum fine-tunes movements and balance. The medulla controls heart rate and breathing, and the hypothalamus regulates temperature and hormones.'},
];
export function shuffle(items){const arr=[...items];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}return arr;}
export function makeRound(topic='mixed',count=8){if(!['mixed',...TOPICS].includes(topic))throw new Error('Choose a valid topic.');if(!Number.isInteger(count)||count<1||count>20)throw new Error('Choose 1 to 20 questions.');return shuffle(QUESTIONS.filter(q=>topic==='mixed'||q.topic===topic)).slice(0,count).map(q=>{const choices=shuffle(q.choices.map((text,i)=>({text,correct:i===q.answer})));return {...q,choices};});}

// Numeric questions: the correct value comes first, followed by the most common wrong answers (a step skipped, a formula reversed),
// then generic multiples as padding. Duplicates after formatting are dropped so every question keeps four distinct choices.
const format=(n,unit='')=>Number(n.toFixed(3)).toLocaleString('en-US')+unit;
function numericQuestion(topic,q,correct,why,{unit='',alts=[],render}={}){
 const show=render||(n=>format(n,unit));
 const pool=[correct,...alts,correct*2,correct/2,correct*10,correct+1,correct+3,correct-1,correct/10,correct+7];
 const choices=[...new Set(pool.filter(n=>Number.isFinite(n)&&n>0).map(show))].slice(0,4);
 QUESTIONS.push({topic,q,choices,answer:0,why});
}
function fractionQuestion(topic,q,correct,alts,why){QUESTIONS.push({topic,q,choices:[correct,...alts],answer:0,why});}

// Cells: surface-area-to-volume ratio, magnification, dilution.
for(let s=1;s<=5;s++)numericQuestion('cells',`A cube-shaped cell has sides of ${s} µm. What is its surface-area-to-volume ratio?`,6/s,`Surface area = 6 × ${s}² = ${6*s*s} µm² and volume = ${s}³ = ${s**3} µm³, so SA : V = ${6*s*s} ÷ ${s**3} = ${format(6/s)} : 1. Larger cells have a smaller ratio, which is why cells stay small.`,{alts:[6*s*s,s**3,s],render:n=>`${format(n)} : 1`});
numericQuestion('cells','A cell drawn from a microscope image is 50 mm wide, and its actual width is 0.05 mm. What is the magnification of the drawing?',1000,'Magnification = image size ÷ actual size = 50 mm ÷ 0.05 mm = 1,000×. Convert both measurements to the same unit before dividing.',{unit:'×',alts:[0.001,50,500]});
numericQuestion('cells','An electron micrograph shows a mitochondrion 20 mm long at a magnification of 10,000×. What is its actual length?',2,'Actual size = image size ÷ magnification = 20 mm ÷ 10,000 = 0.002 mm, and 0.002 mm × 1,000 µm/mm = 2 µm.',{unit:' µm',alts:[0.002,20,200]});
numericQuestion('cells','A light microscope has a 10× eyepiece and a 40× objective lens. What is the total magnification?',400,'Total magnification = eyepiece × objective = 10 × 40 = 400×. The two lenses multiply, they do not add.',{unit:'×',alts:[50,4,4000]});
numericQuestion('cells','You need 100 mL of a 0.5 M glucose solution. What volume of a 2 M stock solution should you dilute?',25,'C₁V₁ = C₂V₂, so V₁ = C₂V₂ ÷ C₁ = (0.5 M × 100 mL) ÷ 2 M = 25 mL of stock, made up to 100 mL with water.',{unit:' mL',alts:[400,50,75]});

// Genetics: Punnett square probabilities and Hardy-Weinberg calculations.
fractionQuestion('genetics','Two heterozygous pea plants (Aa × Aa) are crossed. What fraction of the offspring is expected to be homozygous recessive (aa)?','1/4',['1/2','3/4','1/16'],'The Punnett square gives 1 AA : 2 Aa : 1 aa, so 1 of the 4 boxes is aa. That single box is the recessive quarter of the classic 3 : 1 phenotype ratio.');
fractionQuestion('genetics','In a monohybrid cross Aa × Aa, what fraction of the offspring shows the dominant phenotype?','3/4',['1/4','1/2','9/16'],'AA and Aa both show the dominant trait: 1 + 2 = 3 of the 4 boxes, giving the 3 : 1 ratio Mendel observed.');
fractionQuestion('genetics','In a test cross Aa × aa, what fraction of the offspring is expected to show the recessive phenotype?','1/2',['1/4','3/4','1/8'],'Half of the Aa parent’s gametes carry a, and every gamete from the aa parent carries a, so 2 of the 4 boxes are aa: a 1 : 1 ratio.');
fractionQuestion('genetics','In a dihybrid cross AaBb × AaBb, what fraction of the offspring shows both dominant traits?','9/16',['3/16','1/16','3/4'],'Independent assortment gives the 9 : 3 : 3 : 1 ratio. Multiply the separate probabilities: ¾ (A_) × ¾ (B_) = 9/16.');
numericQuestion('genetics','In a population in Hardy-Weinberg equilibrium, 16% of individuals show a recessive trait (q² = 0.16). What is the frequency of the recessive allele, q?',0.4,'q = √q² = √0.16 = 0.4. The recessive phenotype frequency equals q², so take the square root to recover the allele frequency.',{alts:[0.16,0.6,0.84]});
numericQuestion('genetics','If q² = 0.16 for a recessive trait in a population at Hardy-Weinberg equilibrium, what is the frequency of the dominant allele, p?',0.6,'First q = √0.16 = 0.4. Because p + q = 1, p = 1 − 0.4 = 0.6. Do not subtract q² from 1: 0.84 is the frequency of dominant phenotypes, not of the dominant allele.',{alts:[0.84,0.4,0.36]});
numericQuestion('genetics','In a population at Hardy-Weinberg equilibrium, 9% of people are homozygous recessive for a trait. What percentage are heterozygous carriers?',42,'q = √0.09 = 0.3, so p = 0.7. Heterozygotes = 2pq = 2 × 0.7 × 0.3 = 0.42, or 42%.',{unit:'%',alts:[91,49,30]});
numericQuestion('genetics','A population of 1,000 plants is in Hardy-Weinberg equilibrium and 40 of them show a recessive trait. How many plants are expected to be heterozygous?',320,'q² = 40 ÷ 1,000 = 0.04, so q = 0.2 and p = 0.8. Heterozygotes = 2pq = 2 × 0.8 × 0.2 = 0.32, and 0.32 × 1,000 = 320 plants.',{alts:[960,640,40]});

// Molecular: codons, amino acids, Chargaff’s rules, hydrogen bonds.
numericQuestion('molecular','An open reading frame is 300 nucleotides long. How many codons does it contain?',100,'Each codon is three nucleotides, so 300 ÷ 3 = 100 codons.',{alts:[900,300,150]});
numericQuestion('molecular','A gene’s coding sequence has 600 nucleotides. How many codons is that?',200,'600 ÷ 3 = 200 codons, because the ribosome reads mRNA three bases at a time.',{alts:[1800,600,300]});
numericQuestion('molecular','An open reading frame of 453 nucleotides ends with a stop codon. How many amino acids are in the finished polypeptide?',150,'453 ÷ 3 = 151 codons, but the final stop codon does not code for an amino acid, leaving 150 amino acids.',{alts:[151,453,149]});
numericQuestion('molecular','An mRNA reading frame of 903 nucleotides includes one stop codon. How many amino acids does it encode?',300,'903 ÷ 3 = 301 codons; subtract the stop codon to get 300 amino acids.',{alts:[301,903,299]});
numericQuestion('molecular','A sample of double-stranded DNA is 30% adenine. What percentage of its bases are guanine?',20,'By Chargaff’s rules A = T, so thymine is also 30%, leaving 40% for G + C. Since G = C, guanine is 20%.',{unit:'%',alts:[30,70,40]});
numericQuestion('molecular','In a double-stranded DNA molecule, 22% of the bases are cytosine. What percentage are thymine?',28,'C = G = 22%, so G + C = 44% and A + T = 56%. Because A = T, thymine is 28%.',{unit:'%',alts:[22,78,56]});
numericQuestion('molecular','How many hydrogen bonds hold together 3 G-C base pairs?',9,'Each guanine–cytosine pair is held by three hydrogen bonds, so 3 × 3 = 9. A-T pairs have only two, which is why GC-rich DNA melts at a higher temperature.',{alts:[6,3,5]});
numericQuestion('molecular','A short DNA fragment contains 4 A-T pairs and 6 G-C pairs. How many hydrogen bonds hold the two strands together?',26,'A-T pairs contribute 4 × 2 = 8 bonds and G-C pairs contribute 6 × 3 = 18, for 26 in total.',{alts:[20,10,30]});

// Ecology: the 10% rule, exponential doubling, bacterial generations, growth rate.
numericQuestion('ecology','Producers in a grassland capture 10,000 kJ of energy. Using the 10% rule, how much energy reaches the secondary consumers?',100,'Each transfer passes on about 10%: primary consumers receive 1,000 kJ and secondary consumers receive 10% of that, 100 kJ.',{unit:' kJ',alts:[1000,10,9000]});
numericQuestion('ecology','A pond’s producers hold 50,000 kJ of energy. About how much is available to the tertiary consumers at the fourth trophic level?',50,'50,000 → 5,000 → 500 → 50 kJ: three transfers, each keeping roughly 10% of the energy.',{unit:' kJ',alts:[500,5000,5]});
numericQuestion('ecology','Grasses in a field store 20,000 kJ of energy. Under the 10% rule, how much energy do the grasshoppers (primary consumers) obtain?',2000,'Primary consumers keep about 10% of the producers’ energy: 0.1 × 20,000 = 2,000 kJ. The other 90% is lost as heat, waste, and uneaten tissue.',{unit:' kJ',alts:[200,18000,20]});
numericQuestion('ecology','A population of 50 rabbits doubles every 5 years. Assuming exponential growth, how many rabbits are there after 20 years?',800,'20 years is 4 doubling periods, so N = 50 × 2⁴ = 50 × 16 = 800.',{alts:[400,200,1600]});
numericQuestion('ecology','A yeast culture starts with 100 cells and doubles every 3 hours. How many cells are there after 12 hours?',1600,'12 ÷ 3 = 4 doublings: 100 × 2⁴ = 1,600 cells.',{alts:[400,800,3200]});
numericQuestion('ecology','A single bacterium divides every 20 minutes. How many bacteria are there after 2 hours?',64,'Two hours is 120 minutes, or 6 generations, so 1 × 2⁶ = 64. Exponential growth quickly outruns intuition.',{alts:[6,12,128]});
numericQuestion('ecology','A culture of 1,000 bacteria has a doubling time of 30 minutes. What is the population after 2 hours?',16000,'120 ÷ 30 = 4 generations, so 1,000 × 2⁴ = 16,000 bacteria.',{alts:[4000,8000,2000]});
numericQuestion('ecology','A country has a birth rate of 30 per 1,000 people and a death rate of 10 per 1,000 per year, with no migration. What is its annual population growth rate?',2,'Growth rate = (births − deaths) ÷ population = (30 − 10) ÷ 1,000 = 0.02 per year, or 2%.',{unit:'%',alts:[20,40,3]});

// Physiology: cardiac output, minute ventilation, blood volumes, body temperature, ATP yield.
numericQuestion('physiology','A resting adult has a heart rate of 70 beats per minute and a stroke volume of 70 mL. What is the cardiac output?',4.9,'Cardiac output = heart rate × stroke volume = 70 × 70 mL = 4,900 mL/min, which is 4.9 L/min.',{unit:' L/min',alts:[49,140,0.49]});
numericQuestion('physiology','During exercise an athlete’s heart rate rises to 150 beats per minute with a stroke volume of 100 mL. What is the cardiac output?',15,'150 × 100 mL = 15,000 mL/min = 15 L/min, about three times the resting value.',{unit:' L/min',alts:[1.5,150,250]});
numericQuestion('physiology','A person breathes 12 times per minute with a tidal volume of 500 mL. What is their minute ventilation?',6,'Minute ventilation = breathing rate × tidal volume = 12 × 500 mL = 6,000 mL/min = 6 L/min.',{unit:' L/min',alts:[60,0.6,512]});
numericQuestion('physiology','While jogging, someone breathes 20 times per minute with a tidal volume of 600 mL. What is their minute ventilation?',12,'20 × 600 mL = 12,000 mL/min, or 12 L/min.',{unit:' L/min',alts:[1.2,120,620]});
numericQuestion('physiology','About 55% of blood volume is plasma. In an adult with 5 L of blood, what is the plasma volume?',2.75,'0.55 × 5 L = 2.75 L of plasma; the remaining 45% is mostly red blood cells.',{unit:' L',alts:[2.25,0.55,4.5]});
numericQuestion('physiology','A hematocrit of 45% means red blood cells make up 45% of blood volume. How much red-cell volume is in 6 L of blood?',2.7,'0.45 × 6 L = 2.7 L. The remaining 3.3 L is plasma plus a thin layer of white cells and platelets.',{unit:' L',alts:[3.3,0.45,4.5]});
numericQuestion('physiology','Normal human core body temperature is about 37 °C. What is this in degrees Fahrenheit?',98.6,'°F = °C × 9/5 + 32 = 37 × 1.8 + 32 = 98.6 °F.',{unit:' °F',alts:[37,100,66.6]});
numericQuestion('physiology','Glycolysis yields a net 2 ATP per glucose. If a muscle cell ferments 10 glucose molecules without oxygen, what is the net ATP gain?',20,'Without oxygen, glycolysis is the only ATP-producing step, so 10 × 2 = 20 ATP. Aerobic respiration would yield roughly 30–32 ATP per glucose instead.',{unit:' ATP',alts:[2,40,320]});
