import test from 'node:test';import assert from 'node:assert/strict';
import {QUESTIONS,TOPICS,makeRound,shuffle} from '../src/lib/practice.mjs';
const correctText=q=>q.choices[q.answer];
const find=fragment=>{const q=QUESTIONS.find(x=>x.q.includes(fragment));assert.ok(q,`missing question containing "${fragment}"`);return q;};
test('bank holds exactly 100 unique questions, 20 per topic',()=>{assert.equal(QUESTIONS.length,100);assert.equal(new Set(QUESTIONS.map(q=>q.q)).size,100);assert.deepEqual(TOPICS,['cells','genetics','molecular','ecology','physiology']);for(const topic of TOPICS)assert.equal(QUESTIONS.filter(q=>q.topic===topic).length,20,topic);assert.ok(QUESTIONS.every(q=>TOPICS.includes(q.topic)));});
test('every question has four unique choices, a valid answer index, and a teaching explanation',()=>{for(const q of QUESTIONS){assert.equal(q.choices.length,4,q.q);assert.equal(new Set(q.choices).size,4,q.q);assert.ok(q.choices.every(c=>typeof c==='string'&&c.trim().length>0),q.q);assert.ok(Number.isInteger(q.answer)&&q.answer>=0&&q.answer<4,q.q);assert.ok(q.q.length>20&&/\?$/.test(q.q),q.q);assert.ok(q.why.length>=40&&/\.$/.test(q.why),q.q);assert.doesNotMatch(q.choices.join(' ')+q.why,/NaN|Infinity|undefined/,q.q);}});
test('makeRound returns distinct questions of the requested topic with exactly one correct choice',()=>{for(const topic of ['mixed',...TOPICS]){const round=makeRound(topic);assert.equal(round.length,8);assert.equal(new Set(round.map(q=>q.q)).size,8);for(const q of round){if(topic!=='mixed')assert.equal(q.topic,topic);assert.equal(q.choices.length,4);assert.equal(q.choices.filter(c=>c.correct).length,1);const original=QUESTIONS.find(x=>x.q===q.q);assert.equal(q.choices.find(c=>c.correct).text,correctText(original));assert.deepEqual(new Set(q.choices.map(c=>c.text)),new Set(original.choices));}assert.equal(makeRound(topic,20).length,20);assert.equal(makeRound(topic,1).length,1);}});
test('makeRound does not mutate the bank and rejects unknown topics and bad counts',()=>{const before=JSON.stringify(QUESTIONS);makeRound('mixed',20);assert.equal(JSON.stringify(QUESTIONS),before);assert.throws(()=>makeRound('unknown'),/valid topic/);assert.throws(()=>makeRound('mixed',21),/1 to 20/);assert.throws(()=>makeRound('mixed',0));assert.throws(()=>makeRound('cells',2.5));assert.throws(()=>makeRound('cells',NaN));});
test('shuffle keeps every item and leaves the source untouched',()=>{const source=[1,2,3,4,5,6];const out=shuffle(source);assert.deepEqual(source,[1,2,3,4,5,6]);assert.deepEqual([...out].sort(),[1,2,3,4,5,6]);});
test('generated numeric questions carry textbook-correct answers',()=>{
 assert.equal(correctText(find('sides of 2 µm')),'3 : 1');
 assert.equal(correctText(find('sides of 5 µm')),'1.2 : 1');
 assert.equal(correctText(find('10× eyepiece and a 40× objective')),'400×');
 assert.equal(correctText(find('actual width is 0.05 mm')),'1,000×');
 assert.equal(correctText(find('magnification of 10,000×')),'2 µm');
 assert.equal(correctText(find('2 M stock')),'25 mL');
 assert.equal(correctText(find('homozygous recessive (aa)')),'1/4');
 assert.equal(correctText(find('shows the dominant phenotype')),'3/4');
 assert.equal(correctText(find('test cross Aa × aa')),'1/2');
 assert.equal(correctText(find('both dominant traits')),'9/16');
 assert.equal(correctText(find('frequency of the recessive allele, q')),'0.4');
 assert.equal(correctText(find('frequency of the dominant allele, p')),'0.6');
 assert.equal(correctText(find('9% of people are homozygous recessive')),'42%');
 assert.equal(correctText(find('40 of them show a recessive trait')),'320');
 assert.equal(correctText(find('300 nucleotides long')),'100');
 assert.equal(correctText(find('453 nucleotides')),'150');
 assert.equal(correctText(find('30% adenine')),'20%');
 assert.equal(correctText(find('22% of the bases are cytosine')),'28%');
 assert.equal(correctText(find('3 G-C base pairs')),'9');
 assert.equal(correctText(find('4 A-T pairs and 6 G-C pairs')),'26');
 assert.equal(correctText(find('reaches the secondary consumers')),'100 kJ');
 assert.equal(correctText(find('fourth trophic level')),'50 kJ');
 assert.equal(correctText(find('doubles every 5 years')),'800');
 assert.equal(correctText(find('divides every 20 minutes')),'64');
 assert.equal(correctText(find('doubling time of 30 minutes')),'16,000');
 assert.equal(correctText(find('birth rate of 30 per 1,000')),'2%');
 assert.equal(correctText(find('heart rate of 70 beats per minute')),'4.9 L/min');
 assert.equal(correctText(find('rises to 150 beats per minute')),'15 L/min');
 assert.equal(correctText(find('12 times per minute')),'6 L/min');
 assert.equal(correctText(find('55% of blood volume is plasma')),'2.75 L');
 assert.equal(correctText(find('hematocrit of 45%')),'2.7 L');
 assert.equal(correctText(find('37 °C')),'98.6 °F');
 assert.equal(correctText(find('ferments 10 glucose molecules')),'20 ATP');
});
test('hand-written conceptual questions keep their textbook answers',()=>{
 assert.equal(correctText(find('main site of aerobic respiration')),'Mitochondrion');
 assert.equal(correctText(find('sperm or egg contain')),'23');
 assert.equal(correctText(find('blood type AB and a parent with blood type O')),'Type A or type B only');
 assert.equal(correctText(find('color-blind father and a homozygous normal mother')),'0%');
 assert.equal(correctText(find('adenine always pairs')),'Thymine');
 assert.equal(correctText(find('start codon AUG')),'Methionine');
 assert.equal(correctText(find('oxygen gas released during photosynthesis')),'Water (H₂O)');
 assert.equal(correctText(find('permafrost')),'Tundra');
 assert.equal(correctText(find('pumps oxygenated blood out to the body')),'Left ventricle');
 assert.equal(correctText(find('produce antibodies')),'B lymphocytes (plasma cells)');
});
